### ISSUE TITLE
Changing language while not on a search or gloss page leads to a 403/forbidden error

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#103]
All pages under the 'about' and 'feedback' menus are normally reachable regardless of the language a user is working in. However, changing languages on these pages leads to a 403/forbidden error (with the reason 'CSRF token missing or incorrect'). If you go back in your browser history, all pages under  the 'about' and 'feedback' menus return this error, except when you go back to a search page. (The language does seem to change somewhere in the process.)

**Comment by Woseseltops** [comment]
After trying dozens of things, I've solved it, but I have to admit I'm not fully sure why this works. 

For future reference, let me explain what I understand: 
* Sites can hijack each other. For example, site A can tell the browser 'logged in at site b' = true, and then site B will think the user is logged in.
* There are simple things you can do to prevent this. Django has a very strong protection in the form of CSRF cookies.
* CSRF cookies are activated and should work on the whole site by default; they are created in the 'base template', the template that all Django pages share.
* For unknown reasons, the pages that were created and can be edited in the admin, the CSRF cookies don't show. I can't find any important difference between regular pages and admin created pages
* The solution was to actively tell the view of admin created pages to proect the page with CSRF cookies (which, again, works by default on the rest of the site).

**Comment by Woseseltops** [comment]
PS
'Petje af' for the very detailed and useful bug report!

**Comment by richardbank** [comment]
403 is one of my [specialisms](http://richardbank.nl/nl/error403.html) :-)

**Comment by Woseseltops** [comment]
Wow that is so cool :D
