### ISSUE TITLE
Make "Delete sign" button invisible to guests

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#104]
Users in the Guest group cannot delete signs (luckily), but they do see the Delete Sign button at the top left of the detail view; please remove it there.

**Comment by Woseseltops** [comment]
Done!

(not pushed to Github yet, because for that i first have to merge susan's code, and that takes more time)

**Comment by ocrasborn** [comment]
@Woseseltops : button gone, but also the movie! Did something go wrong here, or is this a separate problem? (My video download plugin still detects something there, but the screen stays white.)

**Comment by Woseseltops** [comment]
I think a separate problem, because I cannot reproduce @ocrasborn . I've just logged in as a guest user, and I can see all videos. Maybe you can close this issue, and then create a new one where you provide more info about your problem (if you still have it?)

**Comment by ocrasborn** [comment]
OK!
