### ISSUE TITLE
Add column 'Groups' to the Django admin list of Users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#106]
To give us a bit more control in user management, add the following to the user list:
* Column that lists for each user all the groups s/he is a member of
* Column that indicates whether or not the user is "active"
* Column that lists the date of last login
* Column that lists the number of times logged in (new field needed?); also add this in detail view of users

**Comment by ocrasborn** [comment]
See also #40

**Comment by Woseseltops** [comment]
Done! It was quite hard to get the groups right, as that is not part of the user or the user profile. I also added the counter field and the counter functionality. Note that it only checks when you actually log in, which in my case is almost never: Chrome keeps me logged in. If you want me to figure out to count these visits as well, let me know.

**Comment by ocrasborn** [comment]
Nah, let's keep it as is.
