### ISSUE TITLE
Make ECV description field multilingual

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#112]
Presently, only the gloss is multilingual (well, bilingual), because of the two separate fields for English and Dutch gloss.
The description field/property/tag of each ECV entry should also be multilingual, based on the various fields that have a Dutch (or other) translation. This is not yet the case for the keywords/translation equivalents, but it is possible for the various phonology fields.

**Comment by vanlummelhuizen** [comment]
Done. @Woseseltops needs to put on the live server of course.
