### ISSUE TITLE
Import CSV function does not work when language = 'nl' 

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#117]
Import CSV function works fine when language = 'en' (e.g.the following output on the  preview page:
>The following changes were detected:
>For testonnoz (3253), Strong Hand changes from None (None) to T (28).
>*Submit button*

When working in Dutch language, the preview page only says 
>De volgende wijzigingen zijn vastgesteld:
>*Submit button*

Other than #92, things don't work under the hood, so this is not merely a front-end display issue.

**Comment by Woseseltops** [comment]
Done
