### ISSUE TITLE
Remove SN/sign number in the selection lists for Morphemes and Related Signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#121]
Upon creating new entries in the tables in the panels Morphemes and Related Signs, a list of possible entries appears as the user starts typing in a gloss. Next to the gloss, either the sign number (in the box itself) or the empty placeholder "SN:null" (in the pull-down menu) appears. Please remove both: all that should appear is the gloss.

![screenshot 2016-01-21 17 39 11](https://cloud.githubusercontent.com/assets/10242207/12473437/2313c140-c066-11e5-9484-1f2177253eed.png)
![screenshot 2016-01-21 17 40 04](https://cloud.githubusercontent.com/assets/10242207/12473438/23f6934e-c066-11e5-9a96-3c963ee73539.png)

(Other change to same panels: #120)
(Earlier #17 we had already removed Sign Number elsewhere in the interface.)

**Comment by ocrasborn** [comment]
@ErwinKomen , would you still have time to look into this? I noticed it also when selecting a morpheme while editing a sign.

**Comment by ErwinKomen** [comment]
I'll have a look at it on wednesday

**Comment by ErwinKomen** [comment]
Notes:
- Auto completion is done by information gathered with ajax queries; see adminviews.py gloss_ajax_complete and morph_ajax_complete. The bracketed (%s) is defined here.
- Requests are made from gloss_edit.js: gloss_bloodhound and morph_bloodhound
- Type-ahead is facilitated in here too: morphtypeahead() and glosstypeahead()

Actions:
- Edited gloss_ajax_complete()
- Edited morph_ajax_complete()
- Edited gloss_edit.js

Should be solved now. Close?
- Gitted
