### ISSUE TITLE
Alter text related to the Morphology panel

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#122]
The Morphology panel is used to list the constituent morphemes of a lexical entry. Please use the term 'morpheme' in two places:
1. Upon adding, the button text should read 'Add morpheme' rather than 'Add morphology definition'
2. Upon deleting, the warning message should read 'Delete this morpheme' rather than 'Delete this morphology'.

![screenshot 2016-01-21 17 42 56](https://cloud.githubusercontent.com/assets/10242207/12473503/cf9f5dde-c066-11e5-8025-b6b9895e8f9f.png)
![screenshot 2016-01-21 17 43 13](https://cloud.githubusercontent.com/assets/10242207/12473504/d174a920-c066-11e5-95ca-072a955991bb.png)

**Comment by ErwinKomen** [comment]
Could be closed now?
