### ISSUE TITLE
Have a temporary version of Signbank running on Applejack

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#125]

**Comment by Woseseltops** [comment]
I have something running at http://applejack.science.ru.nl/asl-signbank/ . It was a loooot of work (installing librariesk fixing permission problems, etc etc), but it went surprisingly smooth.

Current problems / things to do:
* All urls mentioned forget the asl-signbank part, so all links and stylesheets don't work
* It uses the Dutch

**Comment by Woseseltops** [comment]
Important progress yesterday and today: after a long Google-journey through StackOverflow and similar pages, I suddenly realized why all urls were wrong. To fix it, I started a settings file specific to the Signbank version (NGT/ASL) it's used for. Here it is defined that all urls should start with 'asl-signbank'. Whenever a new url is formed somewhere on the site, the code should look in this settings file. 

I'm pretty happy with this setup, because we needed the specific settings file anyway, for example for defining which fields should be visible on both the site and the Django admin. That now works too: if I take away 'handedness' from the settings, for example, it disappears at both places.

**Comment by ocrasborn** [comment]
Good!

**Comment by Woseseltops** [comment]
Yes! The American signs are in! It was a hard task, because I had to write a script that had all database relations (glosses, field choices, keywords, translations) correct in one go. Also, as mentioned by @ocrasborn, there were doubles that had to be removed by a script before it worked.

Could you please have a look, @ocrasborn , and make a list of things that you see have gone wrong?

Things I already noted myself:
* I'm missing some translations
* I'm missing some phonology fields
* I skipped the annotators for now; I've decided I'd rather do it well in one go, and add them as real users

Also to do:
* Look at ecv
* Look at editor fields in admin

**Comment by ocrasborn** [comment]
Well done @Woseseltops ! A few observations, in order of decreasing priority:
1) There was a miscommunication between us about the capitalisation: the translation equivalents should appear in lowercase (correct now), the gloss itself should be in all caps (wrong now).
2) The list view does not yet correctly display the value for Handedness, rather it lists the machine value (and not just the numbers 0-5, but rather: 1-2-3, N/A, None)
3) The field Annotation ID Gloss Dutch (annotation_idgloss) will not be used for ASL; can be left empty and need not appear anywhere. The field label for annotation_idgloss_en can simply be "Annotation ID Gloss", instead of "Annotation ID Gloss (English)" as in the NGT Signbank.
4) Related to previous point, but more generally: what to do with alternative field labels for identical fields between NGT-ASL? The ASL team prefers "Dominant Handshape" for what we call "Strong Hand" (field domhndsh), and "Nondominant Handshape" for what we call "Weak Hand" (subhndsh). Would be nice if we could go along with people's preferences in this even though the nature of the actual field is identical or nearly identical.

**Comment by ocrasborn** [comment]
Other observation: CSV export works.

**Comment by ocrasborn** [comment]
Tried to manually upload a video. Led to the following error: "The requested URL /video/upload/ was not found on this server."

**Comment by Woseseltops** [comment]
Fixed: 
* Capitalisation
* The forgotten translations and phonology is now also imported
* The field choices with handedness (import / capitalization problem)
* The text editor inside the Django admin is now working again

I really want to do today:
* Rename some labels from the settings file
* Hide Annotation id_gloss from the settings file

Possibly also:
* The annotators

**Comment by ocrasborn** [comment]
Great! I removed users that we don't need, but didn't yet add accounts for all the people who appear in the annotator field, so let's save this for later. Could you instead see whether you can fix the video import and especially the ecv export?

**Comment by Woseseltops** [comment]
Done:
* You can now also turn off the separate english id gloss from the settings. It then disappears from the admin and the detail view. Not yet on the page were you can make new glosses, that was too much work for now.
* The ECV button and ECV output is working: http://applejack.science.ru.nl/asl-signbank/static/ecv/asl.ecv No idea what is the quality of the content, though.
* Uploading and viewing videos is working as well. I'm unhappy with the solution, though; because we had no space left on Applejack, I made a symlink to our general tensusers disk. The videos you upload end up in a dir called 'tempglossvideo' :/

Also:
* After some hard thinking I decided that the cleanest way to handle the fact that the ASL signbank needs different label names is to use the language system we already have in place. I started with adding an American English language, but walked into all kinds of problems; too many things have to be fixed and changed, so I'm not going to have this done in time :(.

I final thing I want to note here is that I've postponed syncing the Dutch Signbank. What needs to be done:
* Git pull
* Migrate database (make backups!)
* Update settinsgfile

**Comment by Woseseltops** [comment]
Although there's nothing to see, I cleaned up quite a bit under the hood; something I postponed earlier because of the deadline. The main thing I did was bringing the Dutch signbank to the latest version of the code. This gave some problems both in terms of the database (which wasn't aware yet of all American additions) and of the settings file. The latter problem also influenced the first one, which resulted in me accidently trying to update the American database instead of the Dutch one; I lost 2+ hours before I figured that out. I now have a solution for the settings file I'm pretty happy with, where I store all server specific settings in separate files in one folder (one file per server), and than there is another file where you define which settings file to use. This last file will not be commited.

To do:
* The ECV setting is not yet correct
* Now we have the pretty architecture, clean up the 'IF hostname' logic
* Make an empty settings file template

**Comment by Woseseltops** [comment]
Done: 
* The ECV setting is not yet correct
* Now we have the pretty architecture, clean up the 'IF hostname' logic
* Make an empty settings file template

Next up: get the american-english language working

**Comment by Woseseltops** [comment]
The American language was already fixed in another issue. Spotted problems:
* The search page does not match the American fields yet
* If you log out, you get redirected to the incorrect location
* In various locations (search field, creating a new gloss) the 'English_idgloss' field is not well hidden or hidden at all

* The detail view should be changed some more (not sure what this means yet)

**Comment by ocrasborn** [comment]
Detail view: first column (Dutch gloss) needs to be removed.

**Comment by Woseseltops** [comment]
Fixed:
* If you log out, you get redirected to the incorrect location
* In various locations (search field, creating a new gloss) the 'English_idgloss' field is not well hidden or hidden at all
* The detail view should be changed some more < -- was about the list view

Removing the english field from the 'add new gloss' page was quite a problem, because that means it would always be empty, which would mean it is no longer unique. Workaround: change the POST message this page sends, so the annotation_idgloss_en is set to annotation_idgloss.

**Comment by Woseseltops** [comment]
The ASL-signbank was still displaying the Dutch search fields. Starting at the phonology tab, I know made the search page dependent on what fields were defined in the settings. As a result of this, the ASL signbank automatically shows the correct fields now.

Two remarks:
* Most of the search fields look weird in the ASL signbank, but I see the corresponding fields in the detail view also look weird... probably related to lacking data and/or field choices. 
* We also need to do semantics, but @ErwinKomen is working on something in issue #137 that blocks me from doing that as well; will continue once it's fixed. For the rest no differences, correct?

**Comment by ocrasborn** [comment]
No, not correct, @Woseseltops : the list of fields in Semantics overlaps between NGT-ASL, but is not the same. Better check yourself.

**Comment by Woseseltops** [comment]
I think you might have misread my message, @ocrasborn . I said that the semantics category was different and still needed to be done, but the rest the same. Anyway, I have now updated the semantics category as well!

**Comment by ocrasborn** [comment]
:-)
