### ISSUE TITLE
Make the References in the Morphology table bidirectional

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#128]
We can now link to other signs in the Morphology table to indicate that the gloss is a compound built up from several other signs. We don't see this information with the signs that are used as compound parts in compounds, however.
How to make this more bidirectional? Automatically generate an entry 'Part of compound' in that same table for the compound parts?

**Comment by ocrasborn** [comment]
--> an "appears in" list

**Comment by ErwinKomen** [comment]
I think this issue has been dealt with now:
- The Gloss Detail view gives two lists: (1) all glosses this gloss is a component of, and (2) all component signs used in this gloss, if it is a compound

@ocrasborn : was there anything else to this issue or should it be closed now?

**Comment by ocrasborn** [comment]
Yes, excellent @ErwinKomen !
