### ISSUE TITLE
Show the constituting parts of compounds with the gloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#129]
* In the detail view and in the list view, show between brackets that a sign A is built up of compound parts B and C if these are specified in the Morphology table as Compound Part 1 and Compound Part 2.
* Proposed format: A (B + C)
* Show this with the Annotation ID Glosses (for all languages)

**Comment by ErwinKomen** [comment]
@ocrasborn : we spoke about this again yesterday.
Right now: 
- compound's components are separated by + signs, and the id's are of a smaller font size
- morphemes are separated by , signs and the id's are italic

Should anything else be done here, e.g. provide surrounding brackets?
Or is it okay as it is rightn ow?
