### ISSUE TITLE
Add field 'English Translation Equivalents'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#130]
* Below the Dutch Translation Equivalents
* In fact, thinking of Universal Signbank, as we've reused this field from the Auslan database, it makes more sense to rename the present field to 'translationNL', and use the existing 'translation' for the English Translation Equivalents
* For new content languages, the English Translation Equivalents will always be used, together with at least one local language translation equivalent.
* In fact, this calls for a more dynamic version of this field, being e.g. 'keywords_local', but named "XXX translation equivalents" where XXX is the variable for the spoken language related to the dataset. Thus, the 'NGT Signbank dataset' would need "Dutch translation equivalents" as a field label, the 'Kata Kolok Signbank dataset' would need "Indonesian translation equivalents" as a field label, etc. The field keywords can then always have the field label "English translation equivalents".

**Comment by ocrasborn** [comment]
See Finnish Signbank issue no. 134 on how to implement this in a nice way.

**Comment by henrinie** [comment]
In finsl signbank this is poorly implemented. I can give some ideas of a better way to do this if needed. It is not a priority for us to fix our implementation yet.
I don't think that just adding a field for another language is the best way to do this. You would need to add a field every time you need a new language. I will come back to this next week.

**Comment by ocrasborn** [comment]
See the useful overview on what 'language' can mean in #182 by @Woseseltops

**Comment by ocrasborn** [comment]
Not sure how it is presently implemented in FinSL, but it would make sense to specify both a sign language name and a local spoken language name when creating a new dataset, so that these two strings can be reused for various field names.
