### ISSUE TITLE
Add a second table under Morphology for bound morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#131]
* In the pull-down menu in the present Morphology table, we have a mixed bag of free and bound morphemes. The former are Compound Parts, which can (and should) refer to existing entries in the gloss database. We don't want to enter bound morphemes (like a classifier or number handshape) as free morphemes in the gloss database, simply because they only occur as bound morphemes.
* Proposal: create a second database (next to the first one that contains the glosses) of bound morphemes, to which a second table under the Morphology Panel can refer.
* We should have a detail and a list view for these bound morphemes just like for the glosses (free morphemes). For now, let's start with just having all the Phonology fields to specify these bound morphemes.
* Allow for search
* Add entry 'Bound Morphemes' under the Signs menu that goes to a search + list view like for the glosses
* Alternative solutions welcome!

**Comment by ErwinKomen** [comment]
It seems to me that all of the above points have now been implemented through other issues:
#174 - the "Morpheme" is added to the model (it becomes a separate table in the database)
#175 - one "Gloss" can contain multiple "Morpheme" instances
#177 - new "Morpheme" entries can be entered
#178 - the Morpheme detail view is taken care of
#179 - the Morpheme list view is taken care of + searching is allowed
#180 - the overal search process is extended to focus on glosses, morphemes or a combination

Conclusion: close this issue 131?
