### ISSUE TITLE
Create a tab-separated text format for creating translations that are in the .po file

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#132]
- The .po file is a bit impenetrable to the average translator. Create a simple table view with the English source text in the first column, and the other languages in the second-third-etc. columns
- One such file per foreign language would in principle also do the trick, but as the number of terms to be translated grows, it may be easier to keep things consistent if we would see all languages in a single table
- Create a script for converting the tab-separated text to new/updated .po files for each language

**Comment by henrinie** [comment]
There are programs for editing '.po' files that supposedly make translating easier, you might want to look into them. I have no experience with them myself, so I am not sure if they work with djangos .po files.
I have not used these apps myself, but here are a few examples:
https://poedit.net/
https://localise.biz/free/poeditor

**Comment by ocrasborn** [comment]
Thanks @henrinie , I'll check it out.

**Comment by vanlummelhuizen** [comment]
@ocrasborn, are the suggestions Henri made sufficient? If so, can we close this issue?

**Comment by ocrasborn** [comment]
Yes, let's close this for now, I think Poedit will do the job fine.
