### ISSUE TITLE
Create draft header for the ASL Signbank

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#135]
* Use the attached picture for now
* Background colour in that picture: RGB 27 38 119, #1b2677
* There's no university logo file we can use (yet)

![asl-header](https://cloud.githubusercontent.com/assets/10242207/13142572/451b065c-d63e-11e5-9700-27bcd3d43b31.jpg)

**Comment by Woseseltops** [comment]
It's in, see http://applejack.science.ru.nl/asl-signbank ! It might seem like a relatively small change, but under the hood of both Signbanks all templates, css files and images are now split into two different folders. In the server specific version file you indicate your Signbank specific code, like 'ASL' or 'NGT', and the basis of that it decides which folders to use.

In other words, both Signbank look different, but are using exactly the same code!

**Comment by ocrasborn** [comment]
:-)
Can I already go ahead and edit page text for ASL, like on the home page?

**Comment by Woseseltops** [comment]
Done, I think?
