### ISSUE TITLE
Add Word Class field to NGT templates and search

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#137]
- Field will have been added for the ASL Signbank
- Make field choices editable in Django if this wasn't already done for ASL
- In the detail view, it should appear above Language 
- Add to search options

**Comment by ErwinKomen** [comment]
There are actually two fields: "wordClass" and "wordClass2".
For ASL it has been placed under **Semantics:**
(1)	Word class 1: [function word, modifier, noun, verb, verb;noun]
(2)	Word class 2: [noun, verb]

Suggested actions:
(1) NGT: add one field [wordClass] above [Language] (in the detail view)
(2) ASL: move [wordClass] to position above [Language], 
(3) Both: 
     a] Add a search field for [wordClass]
     b] Place of the search field? Suggestion: "Search by syntax". But this would then only have one field: word class...

**Comment by ocrasborn** [comment]
What @ErwinKomen and I discussed this morning:
* For now we won't create a separate panel Syntax as there'd be too little in it.
* Please put the wordClass for NGT under the glosses above Language; Language may move at some point as we create filters to distinguish multiple languages
Addition:
* The two word class fields for ASL can stay where they are, but if no search fields have been added yet, please do that for both fields, in the Semantics tab if that's where they are in the detail view.
* Consider renaming Semantics to "Syntax and Semantics" for the ASL Signbank; I will ask the American team whether they'd prefer that.

**Comment by ErwinKomen** [comment]
Implementation so far:
1. Extend dictionary/admin.py to handle adding a **new** field category to FieldChoice
2. Add section in dictionary/adminviews.py (GlossDetailView) that adds fields defined in the 'other' section to choice_lists
3. Define the 'other' section by FIELDS['other'] in ngt.py and asl.py
4. Add "Word class" field to the gloss_detail.html template: for the moment only conditionally for NGT

NOTE: this is only the first part of implementing #137, so hold on...

**Comment by ocrasborn** [comment]
@Woseseltops , since @ErwinKomen won't be available the coming weeks, could you change the NGT label from "Word Class 1" to "Word Class"? (ASL has two, that's where it came from; they're now called Lexical Category 1/2, but we only have one)

**Comment by Woseseltops** [comment]
Done. Of course, this broke the translation at the ASL Signbank, so I fixed that as well.

**Comment by ocrasborn** [comment]
@ErwinKomen : what is still left from this issue? Just the search options?

**Comment by ErwinKomen** [comment]
What is done:
1. Search for **word class** is available in NGT signbank (under "Language and basic properties") and in ASL signbank (under "Syntax & Semantics" as Lexical Category 1 & 2)
2. ASL allows (Gloss-detail) editing of Lexical category 1 & 2 (=word class 1 & 2)

Remaining/follow-up:
1. NGT Gloss-detail editing of Word Class is _not operational_ -- needs fixing/implementing

I think this is it. Will this now be assigned to @vanlummelhuizen or @Woseseltops ?

**Comment by Woseseltops** [comment]
It was acting a bit weird because there were no field choices :) . I added one example, and now it works (took me really long to figure out this was it, though)!
