### ISSUE TITLE
Make empty fields easier to edit

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#138]
* Background: At present, absent values are represented by a single en-dash, which the user has to click when in the edit mode in order to select a value. This requires too fine mouse work
* Proposal: simply change the single dash to a series of five dashes -----, or 10 ----------, to help prevent RSI :-)
* Ideally, a single dash would still appear when not in the edit mode, to emphasise that indeed there is no value. When in edit mode, the multiple dashes would appear.

**Comment by Woseseltops** [comment]
Done!

Corner case: when leaving edit mode while still editing a filed, the multiple dashes remain. Looks complicated, will look into it later.
