### ISSUE TITLE
Improve field choices management

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#141]
Possible field choices are editable in the Django admin, however management is cumbersome: field choices appear in a long list that is not searchable and cannot be filtered. Moreover, entry of duplicate field values is possible. Make the following changes to the Django admin:

* Enforce that all field values are unique for any given machine value
* Either/or: 
   * Make a dropdown menu where you choose a field, returning all field choices for that field
   * Make it possible to filter the fields (like in the admin -> dictionary -> glosses)
   * Create a filter list on the right side of the window to filter on fields (again like in the admin -> dictionary -> glosses)

**Comment by henrinie** [comment]
One thing I wonder about FieldChoices is the machine value the user has to set by him/herself. Does it still work that way in NGT SB, and why did you decide to do it like that (there might be some reason I am unaware of)?

On behalf of this issue:
If there are a lot of FieldChoices, some improvements are needed in order to maintain them and reduce the risk of user error.

**Comment by Woseseltops** [comment]
I switched the FieldChoices over to sortable tables, and I added a filter menu for the field attribute. That should already make your life a lot easier @richardbank . (forgot to label this commit: https://github.com/Signbank/NGT-signbank/commit/0700684f12162bd142721c7e694bffa07c03e8b1) 

> Enforce that all field values are unique for any given machine value

I like the idea that @henrinie seems to be suggesting, to fill this field automatically when creating a new field choice. I would then look for the highest machine value, and give the new field choice this value + 1. Okay?

**Comment by ocrasborn** [comment]
OK, @Woseseltops

**Comment by richardbank** [comment]
Thank you, @Woseseltops, :-)

**Comment by Woseseltops** [comment]
Okay, made the machine value read only, and filled automatically with the highest machine value of the chosen field+1 during saving. This means there is a non-editable [empty] machine value before creation, so I added a description saying that it is added automatically. 

I can also make it only read-only during creation (so editable afterwards), if you wish.

**Comment by richardbank** [comment]
I don't see the benefit of your last point, espacially now we can sort the table. Being able to edit the machine value afterwards can only lead to errors.

**Comment by ocrasborn** [comment]
Great @Woseseltops , this will save us a lot of time and errors.
