### ISSUE TITLE
Provide clear error message for login failure

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#144]
When a user tries to log in but his account expiry date has passed ( #40 ), display a message stating "Your account has expired. Please get in touch with your Signbank contact person if you want to keep using the account."

**Comment by Woseseltops** [comment]
Current behavior: you get sent back to login page, just like when your password is wrong. Suggestion: make this issue a bit broader, something like 'Provide clear error message for login failure'.

**Comment by Woseseltops** [comment]
Done!
