### ISSUE TITLE
Allow for uploading image files

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#145]
* To enable the upload of a citation form image of each sign, add an upload button in the edit mode below the video upload location. Revise file names cf. the video file name (GLOSS-number.jpg).
* Display the image in the detail view at the same size as the citation form video right below that video, so above the Feedback links and above the Tags

**Comment by Woseseltops** [comment]
Done. It only showns something when there is something available (so no 'no citation form image' image like we have for videos. The width is automatically resized to make sure the image fits on the page.

Questions:
* Are you aware of the fact that with this new image in edit mode, the left column is much longer than the right one?
* Should this image also be available in the public view of each gloss?
* When uploading, should there be any limitations for size or file extension?

**Comment by ocrasborn** [comment]
Answers:
- I hadn't thought about the layout impact yet; let's see how it works out after we've uploaded a series of test files.
- For now, let's leave the Public view untouched, we're not actively using it.
- I suggest we keep the file size in our own hands, like with the video; file types could likewise be limited to jpg only.
- And about uploading a revised file: yes, let's just silently overwrite it.

**Comment by ocrasborn** [comment]
Bug: I get an error if I click on a gloss in the detail view or in the Recently Added view, referring to the image path.

**Comment by Woseseltops** [comment]
> I suggest we keep the file size in our own hands, like with the video

* So, display an error when width and/or height is not between x and y pixels?
* Do we want to to limit both width and height? (suggestion: yes)
* What should x and y be (suggestion: 0 and 400)? 

> file types could likewise be limited to jpg only.

* So an error message when something is not jpg? What about png?
* Do we also want to try to to check the content of the image, or is checking the file extension enough? Suggestion: extension check enough.

**Comment by ocrasborn** [comment]
About the size: I thought you were referring to file size in KB, not image size, as you mentioned above that the image is automatically resized. I'd prefer to leave the aspect ratio free.

**Comment by ocrasborn** [comment]
Possible confusion here: I was thinking about possibly uploading multiple images under Other Media, but we only want to display one. Would it perhaps be better to split into two types of images, just like for the video: a citation form video that we want to display in the detail view below the video and as a small icon in the list view, for which there would be a separate upload facility just like for the citation form video; then any other images could be uploaded cf. the uploading of other media. For both, we should have a batch upload function.

**Comment by ocrasborn** [comment]
* We never use png for photos, but let's allow for it and see what happens.
* Agree, extension check suffices.

**Comment by ocrasborn** [comment]
Just to be sure, will you also add this to ASL Signbank?

**Comment by Woseseltops** [comment]
> Bug: I get an error if I click on a gloss in the detail view or in the Recently Added view, referring to the image path.

Ah yes forgot about that. Fixed!

> yes, let's just silently overwrite it.

Working now!

> About the size: I thought you were referring to file size in KB, not image size, as you mentioned above that the image is automatically resized. I'd prefer to leave the aspect ratio free.

My bad. No regulations for image width and height then!

> Possible confusion here

I don't understand what the confusion was, be we decided to leave it as I build it.

> Just to be sure, will you also add this to ASL Signbank?

Yes. I always work on one of the Signbanks, and every now and then bring the other up to date. 

Todo: error message when (1) file too many KBs or (2) file extension not ['jpg','png'].

**Comment by Woseseltops** [comment]
Added showing the warnings on the page, but the return format is not functioning yet because of a & instead of ? in the url... will look into this.

**Comment by Woseseltops** [comment]
Fixed the above, but still not satisfied:
* Doesn't seem to work in all cases.
* It looks like the message doesn't go away when you retry.

Also, I kept the size limit really small for testing purposes. Any preference for a real limit?

**Comment by ocrasborn** [comment]
Not really. We could set it to 1MB to make sure it doesn't load too slowly, as long as we can upload larger images in Other Media.

**Comment by Woseseltops** [comment]
Okay 1MB it is. It seems to work now!

**Comment by ocrasborn** [comment]
@Woseseltops : just noticed that the image is not yet visible in the ASL detail view, could you make it appear there as well?

**Comment by Woseseltops** [comment]
What exactly does not work, @ocrasborn . I uploaded this just now, and for me everything seems to work: http://applejack.science.ru.nl/asl-signbank/dictionary/gloss/862/

**Comment by ocrasborn** [comment]
Sorry, @Woseseltops , I forgot to withdraw this unnecessary comment. It just works.

**Comment by Woseseltops** [comment]
Okay, no problem. Was probably a caching issue for you then!
