### ISSUE TITLE
Revise the links below the video in the detail view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#148]
* Leave only "Provide feedback about this sign"
* Move "Report a missing sign" to a new entry in the Feedback menu
* Remove "Report general site feedback" as this is already in the Feedback menu, but while at it, make this menu item work (it's now a short reminder text). The link (to be removed) leads to the page that should be behind the menu item.

**Comment by ErwinKomen** [comment]
Only "Detail View" or also "Word" view, e.g: http://signbank.science.ru.nl//dictionary/words/beiden-1.html

**Comment by ErwinKomen** [comment]
Implementation details:
1 - Remove two <li> entries in dictionary/gloss_detail.html (these make use of feedback/missingsign.html and feedback/generalfeedback.html)
2 - Add two lines for /feedback/missing/ and /feedback/site/ in /signbank/feedback/urls.py

**Comment by ocrasborn** [comment]
Thanks @ErwinKomen . We'll leave the links in the Word view as they are for the moment.
