### ISSUE TITLE
Change video name when ID-gloss is changed in a CSV-import

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#152]
While changing ID-glosses using the import_csv page should be done with caution, it can be a quick way of propagating a change in the lexicon (like changing - into + for certain glosses, e.g. HOUR-2 into HOUR+2 to denote the incorporation of the 2). However, video names are not changed. (See also #65). Please fix.

Moreover, I'm not sure if the compulsory uniqueness of an ID-gloss (or Annotation ID-gloss) is enforced when changing a gloss this way. Please check and if necessary make a new issue?

**Comment by ocrasborn** [comment]
related to #162

**Comment by Woseseltops** [comment]
I am surprised you could even change id glosses with the csv import functionality, because I had to make a fix before I could get it to work. Possibly related to #142 ?

Anyway, while fixing that I also solved the problem this issue is really about, which is that the video name doesn't update; it does now.

**Comment by ocrasborn** [comment]
@Woseseltops : Are the file names currently in line with the glosses then? Or have we made changes to glosses that are not yet reflected in the file names?

**Comment by Woseseltops** [comment]
When a video file name is not in line, Signbank will say the gloss has no video... so I think that the person editing the glossname would have notice that the video dissappears and fixes it. Anyway, if you want I can make a list of all videos that do not appear to be linked to a gloss, so we can diagnose problem cases faster?

**Comment by ocrasborn** [comment]
Yes, please, @Woseseltops

**Comment by Woseseltops** [comment]
Here you go: https://signbank.science.ru.nl/dictionary/get_unused_videos/ . I'm surprised how much is found! The things with the special chars are probably a mistake by the script, though.

**Comment by ocrasborn** [comment]
I copied the link to the wiki page, something brief you could say there about the three categories and how they might have come about?

**Comment by Woseseltops** [comment]
Done https://github.com/Signbank/NGT-signbank/wiki/How-to-show-unused-videos
