### ISSUE TITLE
Upgrade Django and Python

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#154]
See https://github.com/Signbank/FinSL-signbank/issues/146

Steps:
* Upgrade Django in the virtualenv
* Follow any instructions the upgrade process gives
* See to what extent things are broken, try to fix them
* Upgrade any Django dependencies, and verify if the updated function still does what it should do
* Upgrade Python

**Comment by Woseseltops** [comment]
@ocrasborn , I think now is a good time to do this, because:

1. We are about to migrate the ASL Signbank. It would save us some time if on the new server we could just install the latest version of everything instead of trying to get exactly the right version of each dependency (and having to update it later anyway).
2. Both after migrations and upgrades there is an 'unstable period', where errors might pop up in various parts of the application that were working previously. It feels more efficient to merge these two unstable periods into one.
3. Official support for the versions we are working with have been dropped a long time ago. That is, if any bugs are discovered in our versions, they are not fixed (for example: security fixes, which might Signbank vulnerable to hackers).  
4. It happens more and more often that I have to fix a problem that was fixed in newer versions of Django, or that I have a problem that I would not have had in newer versions of Django. To say the same thing in different words: the number of 'peers' we have is shrinking rapidly, making it much harder to solve problems by Googling them.
5. Both Steve and Henri are on recent versions; if we want to use their work, we will have to upgrade.

Downside: 
* There will be an unstable period, as written above.
* This can take anywhere between an hour and a month; I really don't know what will happen.

**Comment by ocrasborn** [comment]
@Woseseltops : green light.

**Comment by henrinie** [comment]
If you update one major version at a time, I believe django will give warnings about things that are deprecated, and about things that will be deprecated in the next versions. It might be safer to do the upgrade this way.
If you want to be absolute on the safe side, you could do like @stevecassidy did, and make tests for signbank before attempting the upgrade.

**Comment by Woseseltops** [comment]
I cloned a local version of Signbank, and from there made a separate branch, and from there started to upgrade Django step by step as advised by @henrinie . I fixed a ton of issues, and I've now got Django version 1.7 working (depending on your definition of 'working'). 

To do:
* Fix the problem with interface language while logged in.
* Figure out what to do with the message:

```
/home/wessel/sb-local/local/lib/python2.7/site-packages/tagging/managers.py:11: RemovedInDjango18Warning: `ModelTagManager.get_query_set` method should be renamed `get_queryset`.
  class ModelTagManager(models.Manager):
```

* Figure out what to do with the message:

```
You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.
```

And after that:
* Upgrade to 1.8
* Upgrade to 1.9
* Upgrade to 1.10
* Upgrade Python to Python 3.

**Comment by Woseseltops** [comment]
Took longer than I wanted, but I fixed the first two points. Only the unapplied migrations, and the NGT-Signbank is ready for Django 1.7! Also, I forgot to mention that I also want to update all dependencies to their latest versions.

**Comment by Woseseltops** [comment]
The migration to Django 1.8 went a lot smoother already (finished within 90 minutes!). I'm getting the hang of this /famouslastwords. I also already updated all dependencies, surprisingly seems to lead to no trouble other than a few migrations.

Next up:
* Upgrade Django 1.9
* Upgrade Django 1.10
* Upgrade Python 3

**Comment by ocrasborn** [comment]
:-)

**Comment by henrinie** [comment]
Great work @Woseseltops 
I recommend that you check the dependencies changelogs just to be sure (if you already haven't done so).
Btw did you also upgrade javascript dependencies?

**Comment by Woseseltops** [comment]
Put wrong version number on commit https://github.com/Signbank/NGT-signbank/commit/f08796fbeb05072382d0ba13b9bccc4572082e59

**Comment by Woseseltops** [comment]
Upgrading to Django 1.9 was a lot harder unfortunately. Among other things, this version no longer accepted the south migration files we still had, so I restarted a new migration history. Also, the unused registration app was giving all kinds of problems. After some time I decided to disable the problematic code, as we're not using this app anyway. But I made it! Only one version to go.

**Comment by Woseseltops** [comment]
I already made a start with upgrading to 1.10... strangely, there were no warnings initially, like at the previous versions, but as soon as I started clicking around a lot of the functionality seems broken again. 

Turns out some of the broken features were already warned in 1.9, but simply missed by me, so I've no downgraded to Django 1.9 to fix these things. Most of it is done, except (note for myself): 'RemovedInDjangoError for add new sign'. After that, I'll reupgrade to 1.10 and start repairing all the broken features 1 by 1.

**Comment by Woseseltops** [comment]
Clicking around in the app and looking around in the code, I found various constructions that were already indicated in 1.9 to be deprecated. I've upgraded them, and now 1.10 runs like a charm!

Next up: upgrading to Python 3.

**Comment by ocrasborn** [comment]
Goed man!

**Comment by Woseseltops** [comment]
Looks like I got working version in Python3 now! 

Only thing that still is not working right now (besides all the problems I have not discovered yet :) ) is that the URL variable as used in templates is empty, leading you to relative instead of static urls ... to be continued.

**Comment by ocrasborn** [comment]
Let me know when I can help testing!

**Comment by Woseseltops** [comment]
The URL problem turned out to be related to my local settings, not the upgrade. Another problem I fixed is that django_mobile did not support Django 1.10, which lead to warnings. As we're not using django_mobile, I've disabled that module (for now?).

Next up:
* Merge my upgraded branch into the master branch, together with @vanlummelhuizen (as he's been working on the master branch)
* Upgrade the Dutch server.
* @ocrasborn can start testing (and maybe can inform the SB users that some extra errors are expected the coming weeks).

**Comment by Woseseltops** [comment]
@vanlummelhuizen had the smart idea to do it the other way around, and merge the master branch into my upgraded branch. We were prepared for trouble, but surprisingly few things went wrong. After a while we found 'only' two problems that need to be fixed before we can merge the upgraded branch into the master branch and 'pull' the whole thing on the production server:

1. For reasons unclear the 'csv' and 'ecv' buttons on the search page no longer work. This seems to be a Javascript problem somehow related to the upgrade.

2. When migrating his local database to accommodate the all the upgrades, @vanlummelhuizen ended up with a database that does have the fully correct format... I have to figure out what to do exactly when going from an 'old Django database' to a 'new Django database' when you're not going step by step like I did.

**Comment by Woseseltops** [comment]
> For reasons unclear the 'csv' and 'ecv' buttons on the search page no longer work. This seems to be a Javascript problem somehow related to the upgrade.

Nope, turns out to be a Django forms problem: since Django 1.10, Django adds the html 'required' attribute to all of its forms, unless explicitly told otherwise. I now explicitly told otherwise :). Found various encoding problems in the process.

**Comment by Woseseltops** [comment]
> When migrating his local database to accommodate the all the upgrades, @vanlummelhuizen ended up with a database that does not have the fully correct format... I have to figure out what to do exactly when going from an 'old Django database' to a 'new Django database' when you're not going step by step like I did.

Hmm, this turned out to be harder than anticipated. The problem is that upgrading our dependency django-reversion also entails upgrading the database. However, some of the older reversion migrations require an old Django version, while the newer migrations require a recent Django version. This was okay when I was upgrading Django and django-reversion step by step on a test database... but now the code is upgraded I cannot redo this process on the production database. I need to be able to migrate the reversion-columns of the database in one go somehow. Might be related to this issue: https://github.com/etianen/django-reversion/issues/559

The best solution (which I tested and works) is to chnage the database structure of the reversion-columns manually, so they match the ones I got from updating a my test database step by step alongside Django. I'll do this next week with the production database. The resulting database can be the starting point for a new test database for the other devs.

**Comment by henrinie** [comment]
Just to let you know and to make sure you don't miss this,
Django 1.11 was released: https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/

I think that you should continue the upgrade path to 1.11, as it is the latest version, and it is a long term support (LTS) version.

**Comment by Woseseltops** [comment]
Thanks for the heads up @henrinie , I just upgraded. This required no changes (as discovered so far); apparently the version of Django 1.10 we'd been using was already really close to 1.11 . I also again merged the work on master by @vanlummelhuizen , and while checking whether his new features worked we discovered some Python 2 code that still needed upgrading.

In summary, I now know have an up-to-date codebase that's working for all features I checked, and I know how to update an old database. Sounds like we're good to go; I plan to put it in production tomorrow.

**Comment by Woseseltops** [comment]
A too bad, I forgot I am dependent on C&CZ for the migration of the production Apache config... and because the question is quite complicated, it might take some time before they get it done :( .

**Comment by Woseseltops** [comment]
In the mean time:
* We moved from Spitfire to Applejack
* My upgraded branch was marged into master
* Put the new upgraded version into production

**Comment by ocrasborn** [comment]
Do the upgrades also apply to ASL (i.e., should I warn them for possible bugs?)?

**Comment by Woseseltops** [comment]
No, upgrading ASL right now would be really inconvenient, as we're about to change servers (right?).

**Comment by Woseseltops** [comment]
Let's close this one; the many smaller errors that this issue caused are handled in separate issues.
