### ISSUE TITLE
Create batch upload script for citation form images

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#157]
Related to #145 , #156 , #20

**Comment by Woseseltops** [comment]
Done:
* writable/import_images
* http://signbank.science.ru.nl/dictionary/import_images

**Comment by ocrasborn** [comment]
@Woseseltops Script works, thanks. Two requests for improvement:
* Remove file from the source folder as soon as it's imported. This leaves a clean folder when things are all OK, and when the script stumbles upon an error (typically typos in our filenames leading to 'gloss not found' message) and the error is corrected, it doesn't re-import the ones that were already successful.
* Better solution for the latter problem: Present a single log message without interrupting the process for the errors, with all errors in a list above the list of files that were imported correctly.
Same for import_other_media and import_videos, if you don't mind me adding this to this same issue :-)

**Comment by Woseseltops** [comment]
Done. Now, the scripts no longer halts at errors, but makes a note and moves on. Furthermore, it deletes all files it has processed correctly. It only works for images and video so far (since they share the same code). If you're happy, @ocrasborn, I'll do the same for OtherMedia.

**Comment by ocrasborn** [comment]
Yaaay! It works and it is such an improvement!

**Comment by ocrasborn** [comment]
oh, not close issue yet, sorry: yet to implement for OtherMedia

**Comment by Woseseltops** [comment]
Done
