### ISSUE TITLE
Adding a new user fails

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#158]
I tried setting up a new user acount, but I get the following error, no matter what I fill in at the number of Logins field:

###### NOT NULL constraint failed: dictionary_userprofile.number_of_logins
Request Method: 	POST
Request URL: 	http://signbank.science.ru.nl/admin/auth/user/add/
Exception Type: 	IntegrityError
Exception Value: 	NOT NULL constraint failed: dictionary_userprofile.number_of_logins
Exception Location: 	/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 450

Pleas fix

**Comment by Woseseltops** [comment]
whoops sorry fixed
