### ISSUE TITLE
Other media don't download

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#161]
I get an error message, even though the media file is on the server. See e.g. http://signbank.science.ru.nl//dictionary/gloss/2861/, the link to http://signbank.science.ru.nl/var/www2/signbank/live/writable/othervideos/2861/Handy_MEDISCH-B_DOKTER-A_ZM.mp4 leads to an error. Path looks odd :-)

**Comment by ErwinKomen** [comment]
1. Line 657 in adminviews.py is supposed to create the correct URL path, but while the database has "othervideos", the search string OTHER_MEDIA_DIRECTORY has "othermedia" in ngt.py

2. I don't see where in signbank/urls.py or signbank/dictionary/urls.py paths that start with "media" are caught.

**Comment by henrinie** [comment]
@ErwinKomen 
The "media" urls are caught in https://github.com/Signbank/NGT-signbank/blob/master/signbank/urls.py#L73
Which should not be used in production (docs for django 1.9):
https://docs.djangoproject.com/en/1.9/howto/static-files/#serving-files-uploaded-by-a-user-during-development

I don't understand how this line you mentioned is supposed work:
https://github.com/Signbank/NGT-signbank/blob/master/signbank/dictionary/adminviews.py#L657
Does 'replace' exists in other_media.path?

**Comment by ErwinKomen** [comment]
@henrinie 
Thanks for pointing to L73 in signbank/urls.py. How did I miss that?!
The L657 in adminviews deals with the first part of the field path in database table "othervideo". It replaces the server-dependent first part by "/media/othermedia".

**Comment by Woseseltops** [comment]
Interesting to see 3 other people talking about my stupid bug :). 

Summary of what happens: 
* I was saving full paths of OtherVideo files in the database, but when we renamed the 'OtherVideos' folder to 'OtherMedia', these paths became dead links.
* In the detail view, the url to these paths was formed out of the path on the server by a simple string replace

I now see this is an ugly and unhandy solution. Instead, I will only save relative paths in the database, and make it into a URL or server path depending on what's needed in other places in the code.

> Which should not be used in production (docs for django 1.9):

Thanks for pointing this out, @henrinie , I've made into issue #163

**Comment by Woseseltops** [comment]
Done, also changed all existing paths in the database

**Comment by Woseseltops** [comment]
Whoops, accidently closes alraedy

**Comment by Woseseltops** [comment]
Done?

**Comment by ocrasborn** [comment]
Works, as far as I can see, thanks.
