### ISSUE TITLE
Movies disappear

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#162]
We haven't been able to trace patterns in this, but the main movie occasionally disappears. Two particular examples are OKTOBER-A and OKTOBER-B. Anique was sure that they were there, her CSV export says the once were there, but they're not on the server in the folder .../OK/, nor do they appear in the interface (obviously). Any clue what might be going on?

**Comment by richardbank** [comment]
Hmmm. How sure is Anique? There is no information in the CSV export whether a gloss has a video or not. I guess there are two things we can do: either let the database know there is/are videos for a gloss, or make regular backups of all the videos and compare them from time to time. I'd opt for the first.

**Comment by ErwinKomen** [comment]
What about adding a class 'GlossVideoHistory' to signbank/video/models.
Each history item could have fields:
- action  (e.g. upload, delete)
- user (the user who undertook the action)
- date (date-time stamp when this was done)
- gloss (the glossid of the sign involved)
- file (not sure if this is possible: the path from which a user uploaded?)
This way there would at least be a history of what went wrong.

**Comment by ocrasborn** [comment]
Sounds like a good idea to me. Please also take into account the automatic import script, see wiki for description of how it works.

**Comment by ErwinKomen** [comment]
Implementation details:
- Adapted video.models.GlossVideoHistory (and tested locally)
- Added 'upload' and 'rename' registration in video.views.addvideo
- Added 'delete' registration in video.views.deletevideo

But I noticed that three different backup/renaming systems have been used:
1) Change extension .mp4 to .mp4_1, .mp4_2, ...
2) Add (or remove) .bak (e.g. Besluiten-B-2919_1.mp4.bak.bak)
3) Add version number before the extenstion, e.g: Besluiten-B-2919_1.mp4
The "deletion" of an existing video appears to use system (2): it attempts to revert one level of .bak suffix.
The "uploading" of a new video over an existing one uses system (1).
Follow-up: sort this out with @Woseseltops .

**Comment by ErwinKomen** [comment]
TODO: "take into account the automatic import script"

**Comment by ocrasborn** [comment]
@ErwinKomen : I was about to add a new issue ('we can't delete users from ASL Signbank'), when I noticed that the resulting error seems to refer to what you're working on: "no such table: video_glossvideohistory". Is this something that will automatically disappear once you're ready, or do we need a new issue for this?

**Comment by ErwinKomen** [comment]
Dear Onno,

It's me indeed that has been working on that table. It should appear once a migration has been done.

@Wessel, could you perform a migration?

Erwin

Verzonden met mijn Windows Phone
________________________________
Van: ocrasborn<mailto:notifications@github.com>
Verzonden: ‎15-‎6-‎2016 15:04
Aan: Signbank/NGT-signbank<mailto:NGT-signbank@noreply.github.com>
CC: Komen, E.R. (Erwin)<mailto:e.komen@let.ru.nl>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [Signbank/NGT-signbank] Movies disappear (#162)


@ErwinKomen<https://github.com/ErwinKomen> : I was about to add a new issue ('we can't delete users from ASL Signbank'), when I noticed that the resulting error seems to refer to what you're working on: "no such table: video_glossvideohistory". Is this something that will automatically disappear once you're ready, or do we need a new issue for this?

**Comment by Woseseltops** [comment]
I can reproduce the behavior mentioned by @ocrasborn ... strange that it only pops up when deleting a user. 

@ErwinKomen , I think you still have the migration file lying around somewhere. Could you add that to the repository, so I can use it to do the migration?

**Comment by ocrasborn** [comment]
This is in ASL-Signbank, just to be clear. Just tried again (deleting dummydummy), getting the following error, see screen shot.
![screenshot 2016-06-17 13 14 00](https://cloud.githubusercontent.com/assets/10242207/16148952/7db6c232-348d-11e6-9a84-fc4870405481.png)

**Comment by ocrasborn** [comment]
@Woseseltops : and if you then have time left today, could you look at this user deletion issue?

**Comment by ocrasborn** [comment]
@ErwinKomen @Woseseltops : can we close this issue?

**Comment by ErwinKomen** [comment]
@ocrasborn @Woseseltops : I think so, yes
