### ISSUE TITLE
Problem with field value RelOriMov: front (1)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#164]
There's something strange with a value for Relative Orientation: Movement (RelOriMov): if I select front in the pull-down menu when editing a sign and click OK, it displays N/A. In the admin, I see value 'front' being associated with machine value 1, and if I search for 'front' I get 70+ hits.

**Comment by Woseseltops** [comment]
I did some investigation, and I think I understand what happened here: when I started implementing field choices, I just started at 1. However, after some time I decided that 1 should always be N/A, and forgot about the fact that 1 was already in use for some fields. The problem thus is that there are two 'human values', one fixed ('N/A') and one dynamic ('Front') for one machine value. When displaying, N/A will always be used, so you only really notice when you know some field should not be N/A.

I looked at the field choices in the admin, and discovered that more field choices have machine value 1:
* Mouth > chin	(location)
* Downwards > forwards	(MovementDir)
* Pronation/supination (OriChange)
* Rotation	 (PathOnPath)

The solution to this problem obviously is to give these fields another machine value, say machine value x... but what should happen to the glosses, @ocrasborn? Can I assume they should also all get machine value x for these fields?

**Comment by Woseseltops** [comment]
I have mended; wrote a script that finds the first unused machine value, and used that one. Then, field for field, I changed all glosses with the old machine value to the new machine value. Some I did manually, using the new Finnish search result bar, for others I just a quick script.
