### ISSUE TITLE
Change references to NGT in the interface to ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#165]
E.g. in the footer; but there may be other places. I'll edit the pages that I can edit in the admin interface, please search for other uses.

**Comment by ocrasborn** [comment]
@Woseseltops , could you still spend half an hour on this today? It's a low effort-high gain issue, as it's screaming the user in the eye even without doing anything :-)

**Comment by Woseseltops** [comment]
Will do.

**Comment by Woseseltops** [comment]
Turns out the footer thingy was inside the language file. I changed it there, and searched the language file for more NGT references (3 others). Is this all?

**Comment by ocrasborn** [comment]
Think so, yes
