### ISSUE TITLE
Uploading pictures in ASL Signbank leads to an error

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#166]
(haven't tested the batch upload yet, this is just when using the picture upload button while editing a sign)

**Comment by Woseseltops** [comment]
Whoops, completely forgot to create the folder where these files are stored in the writable corner of the website. While working on this, I also discovered some other lacking dirs; created those as well.

**Comment by ocrasborn** [comment]
Just tested this; works.
