### ISSUE TITLE
Can't delete a sign under glosses in Django

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#168]
There's a sign without an Annotation ID gloss somehow peeped in in the ASL Signbank (shows up at top of search results). If I try to delete it in the Gloss table in the Django admin, I get an error message.

![screenshot 2016-06-17 15 24 08](https://cloud.githubusercontent.com/assets/10242207/16152030/0e56d568-34a0-11e6-881b-5366dc69aa26.png)

**Comment by ocrasborn** [comment]
@Woseseltops , if this is related to a migration of the db that @ErwinKomen was already preparing, it would perhaps be a good timing to tackle #139 and #137 now?

**Comment by Woseseltops** [comment]
Fixed, I can remove users and glosses again. Was indeed related to a database migration by @ErwinKomen that was not applied to the website databases yet.
