### ISSUE TITLE
Facilitate entering morphemes

### ISSUE THREAD

**Issue by ErwinKomen** [Signbank/NGT-signbank#177]
The detailView of Gloss, section Morphology, should contain three sections (see also #131):
1) List of compounds (glosses) that are part of this word
2) List of morphemes that appear in this word
3) List of "appears in": all the gloss entries in which this entry appears

Notes:
a. make sure the compound-gloss-names link to the gloss
b. make sure the morpheme-names link to the morpheme entries
c. each morpheme should get a "morpheme type" whose value comes from "FieldChoices"; the allowable values are manually entered by @ocrasborn 
d. the "appears in" differs slightly, depending on whether the entry is a Gloss or a Morpheme:
    i. Gloss: "appears in" lists the glosses in which this gloss appears as compound part
    ii. Morpheme: "appears in" lists the glosses in which this morpheme appears as morpheme

If option 1 from #174 is chosen:
- Adapt the existing DetailView for Gloss, section "Morpheme" as above
- Add a boolean field to indicate that this entry is not for a Word, but for a Morpheme

If option 2 from #174 is chosen:
- Create a detailView for Morpheme that basically contains the same fields and functionality as Word glosses
- further as in option 1, but no separate boolean field to indicate that this is a word/morpheme is needed

**Comment by ErwinKomen** [comment]
Started addressing this issue today. It took a lot of work, but now the "detailView" for the Morpheme is available, and users (with the correct permission) can add a new morpheme or view existing morphemes.

Interestingly enough (for me at least) the 'pk' codes for Gloss and Morpheme are combined, so that there is no overlap between them. This is, of course, the consequence of basing Morpheme on Gloss in the models.py. A second consequence is that a morpheme "idgloss" may **not** coincide with a whole sign's (=Gloss's) "idgloss". 

I plan to address the remainder of this issue after vacation.

**Comment by ErwinKomen** [comment]
Adding new morphemes should now be possible:

1. Choose the menu item "Signs/AddNewMorpheme" -- This leads to dictionary/views.py, add_new_morpheme() -- then add_morpheme.html allows specifying the morpheme's gloss and the morpheme type.
2. When the user presses the "Add New Morpheme" button on the add_morpheme.html form, function add_morpheme(request) is called in dictionary/update.py. The four values belonging to the [MorphemeCreateForm] are validated, and if all is well, a new morpheme is created
3. This leads the user to page ROOT/dictionary/morpheme/NNNN?edit
4. The user can now modify the Morpheme Type (see morpheme_detail.html, which ultimately makes use of the "mrptype_choices()" function that is added to the "Morpheme" model)

Everything works fine in the development environment.
The life site will work fine once one or more values for "MorphemeType" have been entered in the "FieldChoices" table by someone with ADMIN rights.

@ocrasborn: please indicate whether this can be closed

**Comment by ocrasborn** [comment]
@ErwinKomen : I've added some MorphemeTypes. When I create a test item (gloss testmorphOC2), I can't seem to edit the phonology fields. Adding a tag leads to an error page. The Edit button has not changed to 'Turn off edit mode', but the presence of the media upload buttons below the video suggests the page is in edit mode.

**Comment by ErwinKomen** [comment]
@ocrasborn: You're right. The changes become effective only after Wessel has applied them 'life' later this week. But feel free to have a look at the development version!

**Comment by ocrasborn** [comment]
@ErwinKomen , I just noticed that the new menu item still needs to be linked to the permissions: only editors and publishers should be able to view it, not researchers and guests.

**Comment by ErwinKomen** [comment]
@ocrasborn: Okay, I have changed that in signbank/urls.py. Only those that have permission to search glosses will now be able to add a morpheme. I hope that covers the target group.
Even searching for a morpheme is now only possible for those that have the permission to search glosses.
(Should become effective on Wednesday or Thursday.)

**Comment by ocrasborn** [comment]
Thanks!

**Comment by Woseseltops** [comment]
Hi @ErwinKomen , I see that you removed the underscores from the choice lists. These are there for a (dirty work-around) reason, see https://github.com/Signbank/NGT-signbank/issues/7 . I'll discuss with you face-to-face :).

**Comment by ErwinKomen** [comment]
@Woseseltops : we sorted this out together, and I came up with a solution in JS for this add-new-morpheme choice list.

@ocrasborn : close this issue?
