### ISSUE TITLE
Facilitate Morpheme detail view

### ISSUE THREAD

**Issue by ErwinKomen** [Signbank/NGT-signbank#178]
If a word is a compound built from multiple glosses (see issue #129):
- Add the GlossId fields in the [Annotation ID Gloss] fields (both English and Dutch)

If a word contains morphemes (related to issue #128?):
- Add the GlossId fields of the morphemes in the [Annotation ID gloss] fields (English + Dutch)

**Comment by ErwinKomen** [comment]
Issue #177 already implemented the Morpheme detail view. 
What is left for this current issue:
* Compound showing: add the GlossID fields of the components in the detail view
* Morpheme showing: add the GlossID fields of the morphemes in the detail view

**Comment by ErwinKomen** [comment]
Implemented first part: show annotation id gloss fields of components (compound-parts) or morphemes in the detail view.

**Comment by ocrasborn** [comment]
@ErwinKomen : To highlight that I'm looking at a morpheme rather than a sign, I suggest we take over the gray background behind all three glosses like you now made for the Dutch gloss in the list view (search results). We can then see whether that is sufficient or whether we need something more prominent.

**Comment by ErwinKomen** [comment]
Adapted admin_gloss_list.html to show the light-gray background for "morpheme" entries.
Note: this is only done when the listview combines Gloss and Morpheme entries.

@ocrasborn : perhaps close issue #178, since this issue actually is about the detail view and the light-gray background only pops up in the List View. Any amendments to this feature might better be treated in #179.
