### ISSUE TITLE
Facilitate Morpheme list view

### ISSUE THREAD

**Issue by ErwinKomen** [Signbank/NGT-signbank#179]
If a word is a compound built from multiple glosses (see issue #129):
- Add the GlossId fields in the [Annotation ID Gloss] fields (both English and Dutch)
- The added GlossId fields should appear **under** the Annotation ID glosses

If a word contains morphemes:
- Add the GlossId fields of the morphemes in the [Annotation ID gloss] fields (English + Dutch)
- The added GlossId fields should appear **under** the Annotation ID glosses

**Comment by ErwinKomen** [comment]
I have extended the GlossListView so that it shows (a) morphemes and (b) components (of compounds) under the Annotation ID gloss fields.
This only *shows* them; doesn't allow clicking through.
Questions:
1 - Should the morphemes and/or the components have a different foreground or background color to distinguish them? May be not necessary, since they already appear on a different line from the gloss.
2 - Should they be clickable (to end up in the detail view of the relevant morpheme or the gloss that is component)?

**Comment by ocrasborn** [comment]
@ErwinKomen : clickable, yes, please. As for the formatting, I'll drop by to see how it looks now.

**Comment by ErwinKomen** [comment]
Morphemes get a light-gray background in the first column (rounded corners)
The first column display also allows clicking through for morphemes.

TODO:
- Separate morphemes by a comma
- Separate components of a compound by '+' signs

**Comment by ErwinKomen** [comment]
Gloss List View and combined Gloss/Morpheme list view: added instances of {% if not forloop.last %} to admin_gloss_list.html
Morpheme list view: the above does not apply here, since no morpheme (should) exist(s) of different morphemes, nor can a morpheme be a compound.

@ocrasborn : close this issue if the listview is okay?

**Comment by ErwinKomen** [comment]
Addressed one more related issue: morpheme list view should facilitate adding a new morpheme including a morpheme type select box.

**Comment by ocrasborn** [comment]
@ErwinKomen : I think it would be useful if we would also see the Morpheme Type in the list view, in a 4th column after Translation Equivalents. Could you still add that, before closing this issue? Or better move to a new issue?

**Comment by ErwinKomen** [comment]
Indeed, good idea. I've added this in the admin_morpheme_list.html. Should be visible now.
