### ISSUE TITLE
Extend searching to morphemes

### ISSUE THREAD

**Issue by ErwinKomen** [Signbank/NGT-signbank#180]
The existing "Search" button should be extended to include three functions:
1) Search for "signs" (words)
2) Search for "morphemes"
3) Search within both "signs" and "morphemes"

The search opitons should be extended with a "morpheme type" selection possibility

Result functionality:
1) If searches (1) "signs" or (2) "morphemes"  are used, then the result view stays as it is
2) If search type (3) "mixed signs and morphemes" is used, then the result view should include an additional column that indicates whether a result is a morpheme or a word

**Comment by ocrasborn** [comment]
Detail: the appearance of the button does change when I select Search Morpheme (and the button widens to include the whole string), but not when I select Search Sign or Morpheme: then it displays Search Sign, although it does execute the combined query.

**Comment by ErwinKomen** [comment]
Should work now.
@ocrasborn : close this issue?

Details:
Button appearance:
1) When searching for signs only: "Search sign" -- this uses /signs/search
2) Morphemes only: "Search morpheme" -- uses /morphemes/search
3) Search mixed: uses /signs/search

The difference between (1) and (3) is in the "search_type" context variable.
I've now passed that on through "adminviews.py", GlossListView, get_context_data(), so that admin_gloss_list.html can use it to determine which button to show.

**Comment by ocrasborn** [comment]
We cannot yet search for "Morpheme Type", can we? Could you add that somewhere, @ErwinKomen ?

**Comment by ErwinKomen** [comment]
Please advise on terminology.
We now have in the "Search by Morphology" box, both for "morpheme" search and "gloss" search:
- Search for gloss with this as morpheme
- Has morpheme type

Both of these have to do with compound signs and their component signs.
Suggestions:
1) Rename these two for a search from "gloss" as follows:
- Search for compound gloss with this as component
- Has compound component of type

2) Remove these options from the morpheme search (since morphemes are not compounds)

3) Add to the gloss search and to the morpheme search:
- Search for gloss with morpheme type  [mrpType-choice-list]

**Comment by ErwinKomen** [comment]
Discussion result...
1) The "Morphology" part of the gloss search becomes (see admin_gloss_list.html):
- Compounds with the following component sign
- Has component type: [morphology_role choice-list]
- Has morpheme type: [mrpType-choice-list]
2) The "Morphology" part of the morpheme search becomes (see admin_morpheme_list.html):
- Has morpheme type: [mrpType choice-list]

**Comment by ErwinKomen** [comment]
@ocrasborn : this has all been implemented now.
If there still is some tidying up to be done: not earlier than 4th week of September for me.

**Comment by ocrasborn** [comment]
@ErwinKomen : I don't see the changes yet, is that correct?

**Comment by ErwinKomen** [comment]
@ocrasborn : Oh no... I see I haven't yet done any of the above after all. Sorry, I was too fast in thinking this was all done. I'm afraid I won't be able to attend to this earlier than the 4th week of September, though. Sorry about that...

**Comment by ErwinKomen** [comment]
Implemented morphology search possibilities:
1) Gloss search (list view), Search by Morphology now contains:
* Signs with the selected Morpheme (select morpheme from dropdown)
* Compound components of a particular type 
* Signs containing a morpheme from the selected morpheme type

2) Morpheme search (list view), Search By Morphology contains:
* Signs containing a morpheme from the selected morpheme type

POSSIBLE FUTURE EXTENSIONS (make **separate** issue)
1) Gloss search (list view): look for **compound** signs that contain a selectable sign as component

Effected files:
signbank/dictionary/templates/dictionary/admin_gloss_list.html
signbank/dictionary/templates/dictionary/admin_morpheme_list.html
signbank/dictionary/adminviews.py
media/js/gloss_search.js  [ADDITION]
signbank/dictionary/forms.py

**Comment by ErwinKomen** [comment]
@ocrasborn : if the implementation suits the needs, then this particular issue might be closed. 
If there are any errors, I could correc them.
Additional functionality is probably better implemented by @vanlummelhuizen or @Woseseltops .
