### ISSUE TITLE
Adapt model and field names for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#183]
Because of their collaboration with another team in the US, please make the following changes for ASL Signbank:

**Change field labels:**
* ID Gloss → Lemma ID
* Thematic Category → Semantic field
* Word class → Lexical category

**Add fields to model, views, and search:**
* "Lexical category notes"; free text field appearing below Lexical category (word class) in the Semantics panel
* "Type of iconicity": list of possible values, editable in Django; initial values: "Perceptual", "Mimetic", "Mixed", "None"

**Change field:**
* Field "Derivation history" should change from a free text field to a Django editable list, initial values: "Compound", "Initialization", "Numeral incorporation", "Fingerspelled loan signs", "Borrowed from another signed language", "Depiction", "n/a". If all is well, the field has not been used for any sign, but there may be test data somewhere that can be discarded.

**Comment by Woseseltops** [comment]
All done! Two assumptions I did:
* The term 'ID gloss' should be translated to 'Lemma ID' on the whole site.
* 'Type of iconicity' is a semantic field.

Finally, I noticed that something really weird is happening at the American detail view: if you click a field to edit, the dashes disappear but nothing happens. This prevents the new fields from being fully functional... I'll investigate now.

PS
I want to add that for this issue I really benefited from two improvements we did earlier: that adding and managing field choices is now much easier... and that the admin view, detail view and search panel are all linked to the settings file. I really only have to add the field on one location, and it is updated all over the site!

**Comment by Woseseltops** [comment]
Ah, I think I got it... you get that problem when there are no field choices defined yet, or when the field is not yet linked to the correct set of field choices. For all fields that have field choices defined, as far as I can see the problem is now gone!

**Comment by ocrasborn** [comment]
@Woseseltops re: PS: good!
One small detail: could you move "Lexical category notes" up in the detail view and the search form, to be right under "Lexical category 2"?

**Comment by Woseseltops** [comment]
Of course, also really easy
