### ISSUE TITLE
Migrate the ASL-signbank to the American server

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#190]

**Comment by Woseseltops** [comment]
@ocrasborn , i looked back at my email, and I can only find info about a VPN . For this VPN, I need a Yale Net ID, for which I need a PIN. This PIN expired June 14 :(.

However, before I request a new one... do you know anything about a server being ready somewhere? Maybe it's useful to arrange that first, as we might not even even need a VPN for this server.

**Comment by ocrasborn** [comment]
I'll go check it out.

**Comment by Woseseltops** [comment]
Any news on this one? I'm going to spend a lot of my time on Signbank in November, so migrating might be a really nice use of that time :). 

Also, let me add another argument to migrate you might not have thought about, @ocrasborn : a lot of stuff on Applejack (the current ASL Signbank server) is set up in a very temporary, quick and non-developer friendly way, which slows down development and debugging, etc. I can of course go and make things easier to work with on Applejack, but I never take the time because I think we could migrate any moment.

**Comment by ocrasborn** [comment]
No news. Thanks for reminding me, I'm moving it to the top of my list for next week.

**Comment by Woseseltops** [comment]
Do before this issue: 
* https://github.com/Signbank/NGT-signbank/issues/154

Do after this issue:
* https://github.com/Signbank/NGT-signbank/issues/278

**Comment by Woseseltops** [comment]
Duplicate of #362
