### ISSUE TITLE
Convert Chinese .po file to .mo

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#191]
* Latest version is in Word (emailed to @Woseseltops just now; I didn't manage to convert it to a text file that I was able to convert (tried Unicode 9 and Chinese encoding, but even in the preview in word's Save As..., there are a lot of squares suggesting something's not going well)
* The source .po was from March 8, 2016

**Comment by Woseseltops** [comment]
I seem to have something working! It was largely a matter of copypasting from the MS Word document, and then fixing all the syntax errors. There were loads of them, but Django fortunately made nice lists for me to work through. I just finished them, compiled the .mo, and now I see Chinese chars everywhere. Two things go wrong:
* Obviously, there is new stuff, for which there is no translation yet.
* Things like page titles, page content, and field choice names do not use the Django translation system, and thus remain empty. Shall I put the English names there, so it's at least not empty?

Note: commits have not been pushed to github yet, as there are commits by both @ErwinKomen and @vanlummelhuizen that need to be merged on the server before I can do that, and I don't have time for that now.

**Comment by ocrasborn** [comment]
Yes, @Woseseltops , please put English placeholders there now, like I've done (been forced to do) for new field choices. I will try to have all the English that's left translated while in Shanghai next week.

**Comment by Woseseltops** [comment]
> commits have not been pushed to github yet

They are now

> please put English placeholders there now

Done. Also required some fixes to the code.

**Comment by Woseseltops** [comment]
Note: I asked my Chinese neighbour to check quickly, and as far as she could tell we had the right Chinese in the right places :).

**Comment by ocrasborn** [comment]
@Woseseltops , in order to facilitate translation of field values in the coming two weeks, could you export all the field - field values as a two-column text file for me? Or ideally, add an export function (that ideally would include all languages in different columns) to the admin pages where I edit the field values? No import function needed at this point, copy-paste is fine for the moment, but I want be able to pass on a file to translators for the field values.

**Comment by Woseseltops** [comment]
This is what you need @ocrasborn  https://signbank.science.ru.nl/dictionary/all_field_choices.tsv . You might to right click 'Save as' to save it the tab seperated values file to your local machine.

I spent way too much time to also add this as a button to the admin, but I couldn't get it done. I now have to stop trying because of time constraints.

**Comment by ocrasborn** [comment]
right right right -- it does ring a bell :-) But I'm glad that you actually remember!

**Comment by ocrasborn** [comment]
right right right -- it does ring a bell :-) But I'm glad that you actually remember!
