### ISSUE TITLE
Add buttons to remove video/image

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#192]
In the edit mode, we have the possibility to upload a new Video or a new Citation Form Image. In some cases, we don't yet have a correct video/image while it is confusing to users to see the old wrong picture. We now use a tag, but this can go unnoticed. It would therefore be helpful to have two buttons to remove the present media.
Suggestion: create a new section in the edit mode above "Upload New Video" called "Delete media", with two buttons: Remove Video and Remove Citation Form Image.

**Comment by Woseseltops** [comment]
I split this up in a few subtasks:
* There already is some delete video functionality; figure out what this does.
* Create a front end, with two nice buttons that appear in edit mode.
* Create a back-end that deletes images and videos.
* Link front to backend

**Comment by ocrasborn** [comment]
Currently, the remove image button removes the video! Please fix and/or finish issue, @Woseseltops

**Comment by Woseseltops** [comment]
Done. Surprised to find out that the remove video already DID work :).

**Comment by ocrasborn** [comment]
:-)
