### ISSUE TITLE
Convert new or updated videos to thumbnail versions

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#197]
For ELAN to show gloss videos quickly, it needs only small versions. For efficiency, the conversion should be done on the server so that downloading will be quick and convert is not left to each individual ELAN instance.

**Comment by vanlummelhuizen** [comment]
@ocrasborn and I think that this can be done when videos are uploaded to Signbank.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , can this one be closed as well?

**Comment by vanlummelhuizen** [comment]
@ocrasborn As far as I'm concerned.
