### ISSUE TITLE
Morpheme detail view tidy-up

### ISSUE THREAD

**Issue by ErwinKomen** [Signbank/NGT-signbank#200]
Several small things to tidy up this view:
1) Replace "Delete sign" by "Delete morpheme"
2) Warning should speak of "morpheme" not of "sign"
3) Search results come up now with a list of "undefined" buttons -- repair as with Gloss Detail View
4) Remove the text "Search results" as in the GlossDetailView

**Comment by ocrasborn** [comment]
:-)

**Comment by ErwinKomen** [comment]
Actions
1) Changed label in "morpheme_detail.html"
2) Changed label in "morpheme_detail.html"
3) Search results: repaired this to show the results of the previous search
4) Removed text "Search results" as in GlossDetailView

@ocrasborn : Everything okay now?

**Comment by ocrasborn** [comment]
@ErwinKomen : this is actually on the sign detail view: when I click on the morpheme link to the right of the _Annotation ID Gloss (Dutch)_, I'm sent to the sign detail view rather than the morpheme detail view.

**Comment by ErwinKomen** [comment]
@ocrasborn : okay, I'll see to that on wednesday

**Comment by ErwinKomen** [comment]
Situation: in Sign Detail View, the URL for morphemes defined for this sign are wrong

Actions:
- Changes in gloss_detail.html, reference to dictionary:admin_gloss_view changed to dictionary:admin_morpheme_view where needed (see dictionary/urls.py)

@ocrasborn : this should work correctly now.

**Comment by ErwinKomen** [comment]
Related to the morpheme detail view tidy up are a few things in the GlossDetailView:
1 - Clicking on a morpheme while *not* in edit mode: should not open edit window
 (note: Clicking on a morpheme while in edit mode should)
2 - Make it possible to DELETE a morpheme
3 - Adding and Deleting morphemes is now not working. Related to issue #121, where I *removed* the gloss's PK. Apparently other parts of the software expect it to be there (sigh...)
4 - Wording: change under Morphology "Type" to "Compound Part"
5 - Compound appearance in "Annotation ID gloss": separator "+" should not be clickable. Also in ListView. Also for MorphemeDetailView and MorphemeListView

**Comment by ErwinKomen** [comment]
Actions:
1 - Added "edit" class to "morpheme-definition_{{morpheme.id}}" in "gloss_detail.html"
2 - Added delete section (around line 428) in gloss_detail.html; added "update_morpheme_definition()" function in "update.py" -- removes the *relation* between a gloss and a morpheme.
3 - Adapted the functions "gloss_from_identifier" and "morph_from_identifier" in update.py to take care of idgloss's that come without a PK (taking into account that idgloss must be *unique*) -- @Woseseltops : please correct me if I'm wrong here!
4 - Changed the wording in gloss_detail.html
5 - Adapted occurrances of gloss lists in Sign Detail View (gloss_detail.html) and Sign List View (admin_gloss_list.html)

@ocrasborn : please check if all of the above changes are well now.

**Comment by ocrasborn** [comment]
All works fine. One refinement necessary: Make the trashcan icon for deleting a morpheme only visible in edit mode, as with the compound components above it.

**Comment by ErwinKomen** [comment]
@ocrasborn : I had taken care of this, but forgot to update "gloss_edit.js". Now that's updated, all should work well (after renewing the browser's cache probably).
