### ISSUE TITLE
Create an easy way to hide the search fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#201]
A simple button or small triangle at the top left that would hide all of the search page above the search results would be very useful, in order to focus on the list of hits, while still having access to the menu bar and the search boxes there.

**Comment by henrinie** [comment]
What if the search tools would be hidden once you press 'search'? You could have your said button to open it up again.

**Comment by ocrasborn** [comment]
Yes, I like that suggestion, thanks @henrinie .

**Comment by Woseseltops** [comment]
Done. I used the collapsing element used in the rest of Signbank, because the users already knows/understands that interface language.

I'll add @henrinie's idea next time!

**Comment by Woseseltops** [comment]
Done! Was way easier than I thought it would be: if there are search arguments in the url, like 'search=wessel&keyword=', I close the query panel, otherwise I show it.

**Comment by ocrasborn** [comment]
* Discovered a small issue while testing #250 in different browsers: on Chrome, the search fields collapse correctly when I initiate a search using the Dutch gloss field, but not when using the English gloss field or translation equivalents. Works fine on Safari/Firefox, though.
* Same problem whether I hit enter after typing or click the Search Signs button.

**Comment by Woseseltops** [comment]
I'm suprised this worked on Safari/Firefox, because I (apparently) only implemented for the first search field :). I now added it also works for the 'English gloss' and 'Translations' search fields.

**Comment by ocrasborn** [comment]
The automatic collapse of search fields upon executing search seems to have been broken -- by the Django/Python updates?

**Comment by vanlummelhuizen** [comment]
I cannot reproduce on Firefox and Chrome (both on Ubuntu) and Safari (Mac). What are you using?

**Comment by ocrasborn** [comment]
hey... now it works again. Safari. High time I clear my cash and reboot I think.

**Comment by ocrasborn** [comment]
Ah, now I found a way to reproduce: the search fields do not collapse when (only) searching for a tag.

**Comment by ocrasborn** [comment]
...and same for when searching for language or dialect. So it appears to be related to that type of search, where you can select one or more items from a box.

**Comment by Woseseltops** [comment]
Ah yes, the current behavior is that it's always collapsed, unless there is nothing in one of the three main search fields. I think this is the behavior that we want:

Way to access the list view|URL (in the current situation)|Collapsed?|
------------------------------------|--------------------------------------|---------------|
Search via top bar|signs/search/?search=wes&keyword=|yes|
Search via separate search page: nothing entered yet|signs/search/|no|
Search via the separate search page: main fields|sortOrder=idgloss&search_type=[...]|yes|
Search via the separate search: more specific fields|sortOrder=idgloss&search_type=[...]|yes|
'All signs' functionality|/signs/show_all/|yes|

So it looks like it should stays collapsed, unless the url is signs/search AND but has no GET keywords arguments.

**Comment by ocrasborn** [comment]
Agree.

**Comment by Woseseltops** [comment]
I did it a bit differently; the search panel now shows when there are no GET keywords AND show_all is false.
