### ISSUE TITLE
Error searching in Django admin

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#203]
I get an error if I search for a simple string (on) in https://signbank.science.ru.nl/admin/video/glossvideo/

**Comment by Woseseltops** [comment]
Interesting, this was configured incorrectly, possibly already by Steve. I found the correct way to do it here: https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields
