### ISSUE TITLE
Colour of buttons

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#205]
Most buttons are blue when they are clickable, but not the two in the edit mode under the panels Notes and Publication, they are grey. They look unclickable, but they're not. Please change to blue.

**Comment by Woseseltops** [comment]
I think you mean 'Notes' and 'Other media', right? If yes: done.

The grey color under notes has been there from the beginning, I'm curious why Steve made it grey and why nobody noticed it until now :).
