### ISSUE TITLE
Change column in CSV export

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#206]
In the CSV export is a column Morphology with machine values (2,3,4) in it, is that right? We would need to have the text values for those machine values in the CSV.

**Comment by ErwinKomen** [comment]
This requires modifying the Gloss List View's render_to_csv_response() function.
Either someone else pick this up, or I could do it, but not earlier than the fourth week of September.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Done. 
@Woseseltops Could you put this in the live version?

**Comment by Woseseltops** [comment]
Done!
