### ISSUE TITLE
For the packages/patches funtionality: in the list of images/videos, also give the gloss ID.

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#212]
In ELAN the ECV should somehow be connected to the Signbank service to use the Signbank videos in ECV lookup. Now the ECV entry IDs have the form 'gloss1234' in which only the numbers indicate ID and 'gloss' is an ever occuring prefix. The package/patch functionality gives media files with names such as 'GEBAREN-A-1234.mp4' in which 1234 is the actual ID and 'GEBAREN-A' the gloss name. 

I would like to only have the 1234 part on both ends so that ELAN does not have to interpret IDs. This also involves changing ECV entry IDs to only 1234 etc. for both the ECV and the corpus files (ELAN files).

See also #186

**Comment by henrinie** [comment]
Could there be a need to have a separate ID for the video?
In FinSL signbank we have multiple videos per gloss, so we use id's for the videos aswell.
It might be a good idea to use the gloss id for the glosses and the video id for the videos.

**Comment by vanlummelhuizen** [comment]
@henrinie Each video belongs to a gloss and ELAN must be able to link a video to a gloss for the displaying of gloss-videos to work (see also https://github.com/vanlummelhuizen/ASL-ELAN/issues/7 and .../8).

**Comment by vanlummelhuizen** [comment]
@Woseseltops I forgot to mention an addition to the server specific setting is necessary:

```
API_FIELDS = [
    'idgloss',
    'annotation_idgloss',
    'annotation_idgloss_en',

]
```

**Comment by Woseseltops** [comment]
> I forgot to mention an addition to the server specific setting is necessary:

Missed this, added it to the settings just now!

**Comment by ocrasborn** [comment]
@vanlummelhuizen , can this be closed now?

**Comment by vanlummelhuizen** [comment]
Yes.
