### ISSUE TITLE
Adapt ECV export for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#213]
The ECV export button for ASL generates an ECV file that has some hard-coded NGT properties, like the name. Moreover, the ECV is bilingual, including the Dutch gloss field that ASL doesn't use. So:
- Change the CV_ID value to "ASL Signbank" (rather than CNGT_RU-lexicon)
- Make it monolingual, containing only the English gloss
- Change the description field: remove the phonology and frequency information, leaving only the comma-separated translation equivalents

**Comment by vanlummelhuizen** [comment]
@ocrasborn @Woseseltops This is done except for the last item. Going to look into that now.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Done.
@Woseseltops In the commit messages I gave instructions for the server specific settings.

**Comment by vanlummelhuizen** [comment]
@Woseseltops To be sure: see also commit message b680a7d

**Comment by Woseseltops** [comment]
Updated the live repo and followed the instruction in the commit messages here: https://github.com/Signbank/NGT-signbank/commit/7e0471322218b6434388c3b945220235e1987a74
