### ISSUE TITLE
Generate still image from uploaded videos.

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#214]
When a video is uploaded, automatically generate a still image to use in the gloss detail view. 
@Woseseltops In case you pick up this issue, ask me for the script I used for bulk processing of existing videos.

See also #197

**Comment by vanlummelhuizen** [comment]
@Woseseltops @ocrasborn Do we need to take care of existing gloss images, e.g. doing crude versioning as with uploaded videos? Cf. video/views.py, r. 42. Or, to look at it a bit differently, are there any images other than those extracted from the videos used as a gloss image?

**Comment by ocrasborn** [comment]
@vanlummelhuizen : I think we would like to have the opportunity to overrule the automatically generated images, yes. So far we've been happy with the middle frame of each video, but there may well be videos for which this doesn't work so well. I'm not sure if that answers your question or whether it generates a new issue: we wouldn't want manually uploaded images to be removed again by a daily process that replaces all images by freshly generated middle frames.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Alright, I will also implement a versioning for images. 

Btw, generating images will not be a daily process, but merely something that happens when a new video is uploaded. Generating still images for existing videos could be a one time thing, but I believe that has already been done (generated by me, uploaded by you). Correct?

**Comment by ocrasborn** [comment]
True, agree, @vanlummelhuizen
