### ISSUE TITLE
Change name of button

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#215]
Naam van knop in screenshot moet zijn "Bewaar nieuwe opmerking". Voor de duidelijkheid ook de Engelse naam veranderen van "Save New" in "Save new note"

<img width="713" alt="screenshot 2016-10-11 12 07 10" src="https://cloud.githubusercontent.com/assets/10242207/19266809/a29d30ee-8fab-11e6-8b7b-5df5565238e6.png">

**Comment by vanlummelhuizen** [comment]
@ocrasborn Er is nu wel 'Vul nieuwe aantekening in' en 'Bewaar nieuwe opmerking', oftewel er wordt niet dezelfde vertaling voor 'note' gebruikt.
@Woseseltops

**Comment by ocrasborn** [comment]
@vanlummelhuizen : Oeps! Goed punt. Laten we dan maar overal 'aantekening' gebruiken, cf. de NL naam van het panel.

**Comment by vanlummelhuizen** [comment]
@ocrasborn OK, done. Nog wel ff wachten tot @Woseseltops het op de live server zet.

**Comment by Woseseltops** [comment]
Done!
