### ISSUE TITLE
Add headers for the two types of morphology (detail view)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#216]
Please add the following headers in the Morphology panel in the detail view: "Sequential Morphology" for the compound parts (the top two parts), and "Simultaneous Morphology" for the list of morphemes (the third/bottom part).

**Comment by susanodd** [comment]
Done.

**Comment by ocrasborn** [comment]
@susanodd , please make the headers visible also when there are no entries in any of the tables.
