### ISSUE TITLE
Add field 'Meaning in this sign' to Morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#220]
* When specifying for a sign that a certain morpheme occurs (in the Morphology panel), we want to specify the "Meaning in this sign". Please add that, as the third column
* In a second column, display the field keywords (re-labeled to 'Abstract meaning' for morphemes, #243 )

**Comment by susanodd** [comment]
I've added the extra column for Meaning in this sign to the interface, but what type of object should this column contain? A morpheme? A string? Or are there multiple meanings within a morpheme from which this should be selected? Or are these to be harvested, Issue #107.

**Comment by ocrasborn** [comment]
This field should be similar in functioning to Translation Equivalents (field name 'keywords'): multiple comma-separated strings are manually entered.

**Comment by susanodd** [comment]
This is taking a lot of time because the database needs an extra field for this. This is inefficient while under construction, since the database keeps needing to be migrated back to the original version to work on other changes, then migrated back to the under construction version. This is best done on a separate branch.

**Comment by ocrasborn** [comment]
@vanlummelhuizen or @Woseseltops , would it be easier for one of you to to do this?

**Comment by ocrasborn** [comment]
The field is there now, I see, but the label is "Description", rather than "Meaning in this sign".

**Comment by Woseseltops** [comment]
Ah right. I've changed the label, and also fixed some layout issues that were extra clear now with the longer name.
