### ISSUE TITLE
Change "suggest texts" in Morphology panel

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#221]
Upon adding compound parts or morphemes in the Morphology panel, the suggest texts in the field where the glosses appear are a bit odd. Please change as follows:
- Sequential morphology: "ID Gloss of Morpheme"  → Annotation ID gloss
- Simultaneous morphology: "ID morpheme/annotation..."  → "Morpheme gloss"

**Comment by ocrasborn** [comment]
Despite the changes by Susan, it doesn't look quite right yet; I've adapted the text above based on what the situation is now. (Perhaps had better reformulated it altogether, will do that next time.)

**Comment by Woseseltops** [comment]
You were talking about the placeholder texts I think. I've updated them, and used this is a nice opportunity to regenate the .po .

**Comment by ocrasborn** [comment]
Ah. Placeholder texts. Yes. Thanks.
