### ISSUE TITLE
Add dataset value to the list view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#227]
* For searches across datasets
* Make it the leftmost column

**Comment by vanlummelhuizen** [comment]
I added a column to the left of the search result list. 

TODO: make it disappear when only searching in one dataset.

**Comment by ocrasborn** [comment]
Proposal: for now always display Dataset; later reconsider hiding it if only one dataset is selected or if someone only has access to one dataset.
