### ISSUE TITLE
Some Chinese text doesn't show up

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#232]
While in Shanghai end of October, I found people to translate the menu items and some pages. They all appear nicely as expected, but not the first menu item (/, Home) and the text field for that (Home) page.

**Comment by Woseseltops** [comment]
I played with this a little bit, and these seem to be two separate issues:
* For the home page content: it seems like all pages don't pick up Chinese content, not just the home page. Switching between English and Dutch works.
* The home menu button is never translated, apparently, regardless of interface language: I changed the Dutch version to 'Thuis', but it still shows 'Home' when I set Signbank to Dutch.
