### ISSUE TITLE
Translations of field choices don't show

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#233]
If I switch interface language to Dutch, I keep seeing the English names for the field choices.

**Comment by Woseseltops** [comment]
Hmm, weird... for me it works in the detail view: both the chosen option and the list of option in edit mode.

Edit: oh, you are probably talking about the list view (= search results)! Correct?

**Comment by ocrasborn** [comment]
No, I was talking about the detail view. But now that I check it on my other computer, it's actually the reverse: detail view OK, list view not. I'll check again tomorrow in different browsers.

**Comment by ocrasborn** [comment]
Checked it in various browsers on two computers: list view field values are not translated, the detail view is OK.

**Comment by Woseseltops** [comment]
Thanks for figuring this out! I discovered that field choices were never translated in the list view; the code there didn't even work well with field choices. I came up with a solution that is sort of elegant.
