### ISSUE TITLE
Correct typo

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#234]
In the Chinese .po file, I came across the following string:
"Welcome to the Sign Search section of the %(langauge)s SignBank. Here\n you can search for a sign using a Dutch translation in the search box\n above, or browse words starting with any letter below.”
* Change langauge to language
* Then also correct in cn/nl translations

**Comment by Woseseltops** [comment]
I found a second similar typo by searching for langau :). Both were mistakes in the templates, so I fixed them there; fixes should now be visible on the live website. 

I also regenerated the .po for Dutch and Chinese, so potential translators don't have to continue looking at ugly typos while they were fixed on the website already :)

**Comment by ocrasborn** [comment]
:-)
