### ISSUE TITLE
Let the webserver server media files, not Django.

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#237]
For now, see also #189, serving of media files is done by Django. This is not a best practice as it eats unnecessary resources. There are ways to let the webserver serve media file while they are still behind authentication.

**Comment by Woseseltops** [comment]
This was solved as part of issue #240 . Authentication is now done via Django, but the serving via Apache. The first (Apache only, no authentication) and second (Django only) approach are now turned off, so if we discover any videos or pictures that no longer show they were apparently still using an earlier approach and should be switched over.

Our solution is documented here: https://github.com/Signbank/NGT-signbank/wiki/Developer-guide#serving-media-files . 

To do:
* Images and videos now ALWAYS require authentication, which is a problem for the radboud signs which should be freely available to everybody.
* It still needs to be done for the ASL Signbank (ASL signbank can't be updated before we fix this)

**Comment by Woseseltops** [comment]
Fixed the first point: I changed the authentication mechanism so that, when the user not logged in, the system checks whether it can show the video anyway because the accompanying gloss is in the web dictionary.
