### ISSUE TITLE
Movies don't load in Safari

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#240]
* Failed to load resource: Plug-in handled load
* Probably started with the move from iframe to html5 video?
* Related to compression (h264 profile must be baseline?): https://www.google.nl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0ahUKEwjBgf7t1cPQAhXCBcAKHR7-COoQFgg7MAI&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F26137211%2Fvideos-not-playing-in-safari-when-using-html5-video-tag&usg=AFQjCNFdVryr081O8rscVM7qI4_Hzp364w

**Comment by Woseseltops** [comment]
I think @vanlummelhuizen knows most about stuff like this :)

**Comment by vanlummelhuizen** [comment]
My assessment is that this problem is caused by the media being behind authentication. If I use the old url (e.g. /static/glossvideo/SC/SCHIETEN-C-88.mp4), which is still working by the way, the video is nicely displayed. 

I will look into this further.

**Comment by vanlummelhuizen** [comment]
I do not have a definitive solution. It may be caused by the method of serving. I could be that Django is serving the media as one big blob of data instead of chuncks now that it is behind authentication. This may be OK for many clients (Firefox, InternetExplorer?), but not for Safari. 

A possible solution may be to let the media be served from outside Django while maintaining the authentication constraint. A technique for this is X-Sendfile. See also http://www.sensibledevelopment.com/2010/11/django-sendfile-an-for-abstraction-large-file-serving-in-django/

@Woseseltops do you have time tomorrow (dec 8) to talk this through?

**Comment by Woseseltops** [comment]
@vanlummelhuizen and me don't really know what is the problem, so for now we're going with the hypothesis that @vanlummelhuizen already partly describes above: it looks like the Safari video player does not want to eat videos in the way Django serves them. Everything worked when Apache was still serving files, but this was changed to Django when we wanted authentication for media files.

A potential fix we will try now is to have Django do the authentication, but leave serving of media files to Apache again. According to this link: http://stackoverflow.com/questions/1156246/having-django-serve-downloadable-files#answer-1158750 this is achievable with just some code changes and of the installation of the Apache module X-Sendfile. I emailed C&CZ the instructions, let's hope it works.

Extra advantage of doing this: even if this does not solve the Safari problem, it is still a more elegant way to serve files.

**Comment by ocrasborn** [comment]
Interesting observation that might help spot the problem: the video loads and plays well in the Public View, but only not in the Detail View. Same movie, right? One is downscaled upon loading, or the other upscaled?

**Comment by Woseseltops** [comment]
@vanlummelhuizen , could you try to reproduce that behavior on your Apple device?

**Comment by vanlummelhuizen** [comment]
@Woseseltops , I reproduced it and on my iMac it works as @ocrasborn describes.

**Comment by vanlummelhuizen** [comment]
This behaviour is not surprising since the video in the Public View is served through the 'static' route, which means it is served by the webserver. Correct, @Woseseltops ?

**Comment by Woseseltops** [comment]
Aah yes of course, sorry @vanlummelhuizen , I should have thought of this. 

PS
Still waiting for C&CZ to respond with S-sendfile :(

**Comment by Woseseltops** [comment]
Update: they installed it, but apparently it needed some more apache configuration, which I now requested.

**Comment by Woseseltops** [comment]
Fixed I think, does it work again in Safari @ocrasborn ?

**Comment by ocrasborn** [comment]
I can't check at the moment @Woseseltops , as I see no search results (only a hit count). Busy with something?

**Comment by ocrasborn** [comment]
Checked by entering a random gloss number: it works. Good!
