### ISSUE TITLE
Search should show no results, make separate 'show all glosses' link instead

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#241]

**Comment by ocrasborn** [comment]
* That is, the menu item Search should just lead to the search form, and not show all hits by default
* The added menu item should read 'Show all signs'; default pagination of 500 items (which the user can already change by the pull-down menu at the top right)

**Comment by Woseseltops** [comment]
Done, I think this will make the whole thing 'feel' a lot faster and user friendly.

Note: the morpheme search page still shows all morphemes, I guess we want it there as well, right?

**Comment by ocrasborn** [comment]
Yes, let's do it the same way there.

**Comment by Woseseltops** [comment]
Done! W.

**Comment by ocrasborn** [comment]
One more request: Please collapse the search form as the default when selecting the menu "Show all signs"

**Comment by Woseseltops** [comment]
Done, fixed in commit e8c4768fb9166277dfdb63363c0ade19b8310de2

**Comment by ocrasborn** [comment]
Thanks; works. Could you implement this for ASL as well, the whole issue?

**Comment by Woseseltops** [comment]
@ocrasborn , you're probably referring to the fact that I forgot to add the page to the menu in ASL signbank, right (because this is part of the database, not the code)? I did it now anyway :).

**Comment by ocrasborn** [comment]
Indeed!
