### ISSUE TITLE
Change field label of 'keywords' from "Translation Equivalents" to "Abstract Meaning" for morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#243]

**Comment by susanodd** [comment]
Done.

**Comment by susanodd** [comment]
Done == Did first part (Issue description, "Abstract Meaning".)

**Comment by ocrasborn** [comment]
@susanodd , the label is now also used for signs (like in the list view of signs/search results), but the request was only to use "Abstract meaning" for Morphemes. Could you make it such that there are two labels, one for the morphemes (Abstract meaning) and one for the signs (Translation equivalents)?

**Comment by susanodd** [comment]
I fixed the label for signs so it's back to Translation Equivalents instead of Abstract meaning.
