### ISSUE TITLE
When deleting a gloss on the website, you get a reversion error

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#244]
It works, though. The error:

`int() argument must be a string or a number, not 'NoneType'
`

The object to be deleted seems to have lost its pk . 

Related error: https://github.com/etianen/django-reversion/issues/272

**Comment by ocrasborn** [comment]
Also on ASL Signbank

**Comment by Woseseltops** [comment]
I think I fixed it following the suggestions in the reversion github issue (I'm quite surprised this works!).
