### ISSUE TITLE
Problem uploading movie files

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#245]
On 30 nov. 2016, at 12:45, Ros, J.M. (Johan) <j.ros@let.ru.nl> wrote:

Onno,
 
Ik kan nog steeds geen film uploaden bij signbank, en krijg steeds foutmelding.
 
Gr. Johan

**Comment by henrinie** [comment]
What is the error message?

**Comment by ocrasborn** [comment]
OSError at /video/upload/
[Errno 13] Permission denied: '/var/www2/signbank/live/repo/signbank/media/glossvideo'
Request Method:	POST
Request URL:	https://signbank.science.ru.nl/video/upload/
Django Version:	1.6.1
Exception Type:	OSError
Exception Value:	
[Errno 13] Permission denied: '/var/www2/signbank/live/repo/signbank/media/glossvideo'
Exception Location:	/usr/lib/python2.7/os.py in makedirs, line 157
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg',
 '/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7']
Server time:	do, 5 Jan 2017 12:57:40 +0100
Traceback Switch to copy-and-paste view

/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/signbank/video/views.py in addvideo
            video.save() ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/base.py in save
                       force_update=force_update, update_fields=update_fields) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/base.py in save_base
            updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/base.py in _save_table
            result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/base.py in _do_insert
                               using=using, raw=raw) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/manager.py in _insert
        return insert_query(self.model, objs, fields, **kwargs) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/query.py in insert_query
    return query.get_compiler(using=using).execute_sql(return_id) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/sql/compiler.py in execute_sql
        for sql, params in self.as_sql(): ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/sql/compiler.py in as_sql
                for obj in self.query.objs ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/fields/files.py in pre_save
            file.save(file.name, file, save=False) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/db/models/fields/files.py in save
        self.name = self.storage.save(name, content) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/core/files/storage.py in save
        name = self._save(name, content) ...
▶ Local vars
/var/www2/signbank/live/virtualenv/signbank/lib/python2.7/site-packages/django/core/files/storage.py in _save
                os.makedirs(directory) ...
▶ Local vars
/usr/lib/python2.7/os.py in makedirs
            makedirs(head, mode) ...
▶ Local vars
/usr/lib/python2.7/os.py in makedirs
    mkdir(name, mode) ...
▶ Local vars
Request information

GET
No GET data
POST
Variable	Value
redirect	
u'/dictionary/gloss/4340/?edit'
csrfmiddlewaretoken	
u'FFeheCb5d6oow2jLbcUoHxlYIZ6b0bnn'
gloss_id	
u'4340'
FILES
Variable	Value
videofile	
<InMemoryUploadedFile: ROLSTOEL-D-4340.mp4 (video/mp4)>
COOKIES
Variable	Value
csrftoken	
'FFeheCb5d6oow2jLbcUoHxlYIZ6b0bnn'
sessionid	
'z87u7ans55n5nn3u5vt3jhla8elldr6i'
META
Variable	Value
mod_wsgi.listener_port	
'443'
HTTP_REFERER	
'https://signbank.science.ru.nl//dictionary/gloss/4340/'
mod_wsgi.listener_host	
'131.174.16.34'
CONTEXT_DOCUMENT_ROOT	
'/var/www2/signbank/live/htdocs'
SERVER_SOFTWARE	
'Apache/2.4.7 (Ubuntu)'
SCRIPT_NAME	
u''
mod_wsgi.enable_sendfile	
'0'
mod_wsgi.handler_script	
''
SERVER_SIGNATURE	
'<address>Apache/2.4.7 (Ubuntu) Server at signbank.science.ru.nl Port 443</address>\n'
REQUEST_METHOD	
'POST'
PATH_INFO	
u'/video/upload/'
HTTP_ORIGIN	
'https://signbank.science.ru.nl'
SERVER_PROTOCOL	
'HTTP/1.1'
QUERY_STRING	
''
SSL_TLS_SNI	
'signbank.science.ru.nl'
CONTENT_LENGTH	
'1664821'
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36'
HTTP_CONNECTION	
'keep-alive'
HTTP_COOKIE	
'sessionid=z87u7ans55n5nn3u5vt3jhla8elldr6i; csrftoken=FFeheCb5d6oow2jLbcUoHxlYIZ6b0bnn'
SERVER_NAME	
'signbank.science.ru.nl'
REMOTE_ADDR	
'131.174.132.144'
mod_wsgi.queue_start	
'1483617459390221'
mod_wsgi.request_handler	
'wsgi-script'
wsgi.url_scheme	
'https'
PATH_TRANSLATED	
'/var/www2/signbank/live/repo/signbank/signbank/wsgi.py/video/upload/'
SERVER_PORT	
'443'
wsgi.multiprocess	
False
mod_wsgi.input_chunked	
'0'
SERVER_ADDR	
'131.174.16.34'
DOCUMENT_ROOT	
'/var/www2/signbank/live/htdocs'
mod_wsgi.process_group	
'signbank'
SCRIPT_FILENAME	
'/var/www2/signbank/live/repo/signbank/signbank/wsgi.py'
SERVER_ADMIN	
'[no address given]'
wsgi.input	
<mod_wsgi.Input object at 0x7f351867b530>
HTTP_HOST	
'signbank.science.ru.nl'
CONTEXT_PREFIX	
''
wsgi.multithread	
True
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_CACHE_CONTROL	
'max-age=0'
REQUEST_URI	
'//video/upload/'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
mod_wsgi.callable_object	
'application'
wsgi.version	
(1, 0)
GATEWAY_INTERFACE	
'CGI/1.1'
wsgi.run_once	
False
wsgi.errors	
<mod_wsgi.Log object at 0x7f351867ba70>
REMOTE_PORT	
'50514'
HTTP_ACCEPT_LANGUAGE	
'nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4'
REQUEST_SCHEME	
'https'
mod_wsgi.version	
(3, 4)
CONTENT_TYPE	
'multipart/form-data; boundary=----WebKitFormBoundaryMgjSs0VCct1aPAcJ'
mod_wsgi.application_group	
'signbank.science.ru.nl|'
mod_wsgi.script_reloading	
'1'
wsgi.file_wrapper	
''
CSRF_COOKIE	
u'FFeheCb5d6oow2jLbcUoHxlYIZ6b0bnn'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, br'
Settings
Using settings module signbank.settings.base

**Comment by Woseseltops** [comment]
Fixed. Also updated and tested the ASL Signbank
