### ISSUE TITLE
Make listing of morphemes in List View consistent

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#248]
* Under the Annotation ID Gloss: Dutch, the number of morphemes is listed when more than three, under Annotation ID Gloss: English, all morphemes are listed irrespective of the total number. Please revise so as to always provide a count when more than three (cf. the Detail View, where both for "Annotation ID Gloss (Dutch)" and "Annotation ID Gloss (English)" it says "(4 morphemes)"

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by ocrasborn** [comment]
you're getting up to speed, Mr. @vanlummelhuizen !! :-)

**Comment by vanlummelhuizen** [comment]
Just low hanging fruit :)
