### ISSUE TITLE
Adapt script that updates ECV

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#254]
Make sure that it restricts itself to one specific dataset.

**Comment by ocrasborn** [comment]
See also #253

**Comment by susanodd** [comment]
The ECV export now only saves Dataset NGT. (Default.)
(I push this to github but mistakenly called it Issue #111.)

**Comment by ocrasborn** [comment]
Ah good! A very important step. Now on to next horizon: #253 ;-)

**Comment by vanlummelhuizen** [comment]
@susanodd Could you make the code more save? I.e. check whether the NGT dataset exists. While you are at it, perhaps also make the name of ECV-dataset a setting? For NGT Signbank it is 'NGT'. For another Signbank it might be another.

**Comment by vanlummelhuizen** [comment]
@ocrasborn this is live now by the way.

**Comment by susanodd** [comment]
Yes, I can make it safe, but not quite sure what to set it to if NGT isn't found.
Previously, the code didn't look at Dataset at all and just fetched all the Glosses that aren't Morphemes. To be safe I'll make it do that. But yes, there should be a ECV-dataset setting.

**Comment by Woseseltops** [comment]
@vanlummelhuizen and @susanodd , you seem to be working on this, so I'll assign the issue to you guys. In case it's already fully working, reassign to Onno so he can verify and close.

**Comment by ocrasborn** [comment]
Is this already addressed now that #387 has been addressed, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
I believe it is. I will close it now.
