### ISSUE TITLE
Generate image for batch-uploaded videos

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#255]
See #214 : only works for images uploaded through the edit interface.

**Comment by vanlummelhuizen** [comment]
Solved and tested locally. This can be tested in the live server when @Woseseltops merges this code with the code on the server.

**Comment by vanlummelhuizen** [comment]
I also added a Signbank entry to create still images for all gloss videos: <signbank-host>/video/create_still_images/. Note that this process may take quite some time, perhaps even hours for the amount of videos the NGT-Signbank has.

@ocrasborn, do we needs to put this behand authentication?

**Comment by ocrasborn** [comment]
Yes please! Let's make it only available to the group Publisher, as it won't be needed very often and as it takes so much processing time.

**Comment by ocrasborn** [comment]
I might have initiated the process by using the above entry in the url, but what I get is the message 'The requested page was not found on the server' -- is it simply not yet live?

**Comment by vanlummelhuizen** [comment]
I guess @Woseseltops did not merge my commit into the live server yet. Hopefully he has some time this thursday.
