### ISSUE TITLE
Can't remove entries in Relations to Other Signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#258]
The trash can shows, but clicking it has no effect.

**Comment by Woseseltops** [comment]
Same goes for relations to Foreign Signs. I solved this problem the classic way: I got all frustrated for not being able to find the problem for over 60 minutes, and when I got back from lunch I saw it in 5 minutes :). It was a stupid naming mismatch that must have been there for a loooong time, as I don't remember touching this code.

**Comment by ocrasborn** [comment]
Haha! Long live lunch.
