### ISSUE TITLE
Allow for entering multiple identical morphemes in a sign

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#261]
* That is, a morpheme with the same gloss. (Other properties will differ, like the meaning in context.)
* Currently, one can add one that is identical to one that is already there, but upon saving nothing happens (no error, no second entry in the morpheme table).

**Comment by Woseseltops** [comment]
After some looking around in the code, I understand what is going on here. We have a database of glosses, and a databases of morphemes. For this functionality, these are linked directly as a ManyToMany relation called morphemePart, identified in the gloss. When you add the same morpheme twice, it tries to create a connection that was already there, so nothing changes. The solution would be to put an extra object in between (normal in Django, also done in various other places in Signbank) that represents the a connection between a gloss and a morpheme. So definitely possible, but more time consuming than you probably thought, @ocrasborn .

Also, before I do this: I'm confused about the various representations of morphology in Signbank. I the interface I see:
* sequential morphology
* simultaneous morphology
* components
* morphemes

In the code I see
* Morpheme
* Morphology definitions
* Morphemepart

I have no idea how all of these relate to each other. Maybe we could organize a meeting with @vanlummelhuizen  to organize this for ourselves?

**Comment by ocrasborn** [comment]
It's extra messy as @susanodd is in the process of revising some of the labels, and I think my instructions were not always clear or perhaps even not consistent. @vanlummelhuizen also suggested we sit down to discuss it, just like you suggest. We picked Wed 1 Feb for this 11am, but didn't check whether that's a Nijmegen day for you. If not, we'll move it to Thursday.

**Comment by IngZwi** [comment]
Any news here?

**Comment by vanlummelhuizen** [comment]
@Woseseltops  said:

> The solution would be to put an extra object in between (normal in Django, also done in various other places in Signbank) that represents the a connection between a gloss and a morpheme. So definitely possible, but more time consuming than you probably thought, @ocrasborn .

Unfortunately, this procedure interferes with the Signbank-system upgrade process @Woseseltops is now doing. From what I heard it looks like he is almost done, but almost could mean anything, when several unforseen problems may still come up. So fingers crossed.

It's good you asked. It will give us some extra notion of priority.

**Comment by Woseseltops** [comment]
>  From what I heard it looks like he is almost done

Correct. It's done and working on a separate branch already; I plan to merge to the master branch this week. I expect several problems to show up still, but enough of the main functionality seems to be working to put it in production.

> It's good you asked. It will give us some extra notion of priority.

Agreed

**Comment by ocrasborn** [comment]
See #220 : values for this new field can be different for multiple entries of the same morpheme

**Comment by ocrasborn** [comment]
It's not yet working, right, @Woseseltops ? Branch yet to be merged?

**Comment by Woseseltops** [comment]
This has been done already:
* Added a new abstract layer between glosses and morphemes. This new model also has a description field where you can describe the relation in text
* Replaced the old architecture with the new one in the detail view. You can see this one allows double morphemes here: https://signbank.science.ru.nl//dictionary/gloss/3283/
* Populated the new table with all the simultaneous morphology that was already defined (copying from the old to the new system)

To do:
* Make creating, deleting and updating (that is, only the R in CRUD is done so far) work again.
* Look for other usages of the old system and update them.

Note that the definitions are also still 'alive' in the (now invisible) old system. I suggest we remove them there after some time once this new system makes people happy. I created #350 for that.

Also this issue inspired #351: refactoring variable names into something more clean and clear.

**Comment by Woseseltops** [comment]
Added wrong number to commit b397ad9

**Comment by Woseseltops** [comment]
Right, so creating and deleting simultaneous morphology is now also possible. When I wanted to start on updating, I discovered this was never implemented in the old system, which makes me thing it's maybe not worth the effort (you can also delete and create a new relationship)? What do you think @ocrasborn ?

**Comment by ocrasborn** [comment]
We discussed this face to face last week; let's leave the updating (editing) for now. Can be closed?

**Comment by IngZwi** [comment]
Hoi jongens,

Ik weet niet waar dit precies over gaat. Ik heb gemerkt dat morfemen nu weer te editen zijn, da’s fijn! Maar toevoegen van simultane morfologie aan ID-glossen lukt op het moment helemaal niet. Anyway, ik geloof dat het vakantietijd is, dus nu even niet.

Groetjes,
Inge

Van: ocrasborn [mailto:notifications@github.com]
Verzonden: woensdag 12 juli 2017 13:07
Aan: Signbank/NGT-signbank <NGT-signbank@noreply.github.com>
CC: Zwitserlood, I.E.P. (Inge) <i.zwitserlood@let.ru.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [Signbank/NGT-signbank] Allow for entering multiple identical morphemes in a sign (#261)


We discussed this face to face last week; let's leave the updating (editing) for now. Can be closed?

**Comment by Woseseltops** [comment]
Hmm that's weird. I did some more extensive checks after the comments by @IngZwi, and it turns out it works for some glosses, but not for others :( . I'll investigate why.

**Comment by Woseseltops** [comment]
Update: it appears to be related to displaying, everything is saved to the database correctly.

**Comment by Woseseltops** [comment]
Forgot to mention that I (think I) fixed this Wednesday last week. Close?

**Comment by IngZwi** [comment]
Het werkt, hoera!
Van mij mag je ’t afsluiten, maar ik ga daar niet over … ;-)
i.

Van: Wessel Stoop [mailto:notifications@github.com]
Verzonden: donderdag 20 juli 2017 12:16
Aan: Signbank/NGT-signbank <NGT-signbank@noreply.github.com>
CC: Zwitserlood, I.E.P. (Inge) <i.zwitserlood@let.ru.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Signbank/NGT-signbank] Allow for entering multiple identical morphemes in a sign (#261)


Forgot to mention that I (think I) fixed this Wednesday last week. Close?
