### ISSUE TITLE
Don't automatically collapse panels

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#263]
In NGT Signbank, opening a panel in the detail view automatically closes the previous open one. Please make this cf. FinSL Signbank: opening one does nothing to the others, and it's under user control how many to keep open or closed.
@henrinie , could you give us a quick pointer to where this is? Or is that all too trivial for @Woseseltops to find?

**Comment by henrinie** [comment]
I don't remember what I have done differently.
It needs a closer look for me at least. If @Woseseltops doesn't have time to do that, I can do it for you.

**Comment by ocrasborn** [comment]
Oops, I see now that this issue is identical to #259 ; I'll close the latter one.

**Comment by Woseseltops** [comment]
Done; turned out to be a bootstrap thingy.

(not pushed to Github yet, because for that i first have to merge susan's code, and that takes more time)

**Comment by ocrasborn** [comment]
Great!
