### ISSUE TITLE
Correct typo

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#267]
In the Dutch interface, it says 'woorsoort' somewhere, instead of 'woordsoort'. Please correct.

**Comment by susanodd** [comment]
Fixed

**Comment by ocrasborn** [comment]
@Woseseltops @vanlummelhuizen Could you check why this is not online yet?

**Comment by Woseseltops** [comment]
I actually already knew without checking, @ocrasborn :) ... The translation was there, but it was not 'compiled yet' (see https://github.com/Signbank/NGT-signbank/wiki/How-to-translate-texts-for-Signbank#making-changes-visible-online) . I ran the command, and now it is!
