### ISSUE TITLE
Movies don't play in Public View

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#270]
* See discussion at end of #104
* Tested on Mac, Safari/Firefox/Chrome
* Pattern: video's in public view show up and play fine when logged in and then switched from detail to public view. They do not show when not logged in (which is really what the public view is for).

**Comment by Woseseltops** [comment]
Can you give step by step instruction on how to reproduce this problem, @ocrasborn ? The problem doesn't show up (on Linux) when I visit for example https://signbank.science.ru.nl/dictionary/gloss/FACULTEIT.html, not logged in: the video starts playing immediately.

**Comment by ocrasborn** [comment]
Er... now it work again! (Chrome/Safari) Don't know why the player had an off-day, closing for now.
