### ISSUE TITLE
Relations to other signs doesn't seem to work for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#274]
* I don't get suggestions for glosses already in signbank, like it should and like in the NGT version
* While at it, could you double-check it lists annotation ID glosses, and not (as the text in the field suggests) lemma glosses?
* And while at it, could you change the suggest text to "Annotation ID gloss"?

**Comment by Woseseltops** [comment]
> I don't get suggestions for glosses already in signbank, like it should and like in the NGT version

Fixed. Problem was with the fact that we use a sub-url for the temporary location.

> , could you double-check it lists annotation ID glosses,

The line of code:

`result.append({'idgloss': g.idgloss, 'annotation_idgloss': g.annotation_idgloss, 'sn': g.sn, 'pk': "%s" % (g.idgloss)})`

> And while at it, could you change the suggest text to "Annotation ID gloss"?

Done. It will be this in the Dutch signbank too.

**Comment by Woseseltops** [comment]
Note: commited, but not pushed yet, because I have to review Susans code first before merging it.
