### ISSUE TITLE
Automatically create the reverse relation to other sign

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#275]
* When specifying sign B is related to sign A (the one being edited), automatically add the reverse relation for sign B.
* Homonyms, synonyms, and antonyms should get the same type; hypernyms and hyponyms should get the opposite type
• Upon deleting one member of the pair, also delete the other member.

**Comment by ocrasborn** [comment]
Perhaps the code @ErwinKomen wrote to make the morphology links bidirectional can be reused, see #128

**Comment by vanlummelhuizen** [comment]
Done. 

Note that when creating a relation, the reverse is also created, even if the reverse already exists. This is because identical relations may occur more than once. When deleting a relation, the first found reverse relation is deleted.

**Comment by ocrasborn** [comment]
That should be fine: after we do some initial cleaning up, new 'doubles' should not be created anymore thanks to this new functionality. I'll keep the issue open for me to test.
