### ISSUE TITLE
Update ASL ECV every night

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#278]
* I thought we already had this implemented, cf. NGT, but just tested it: a gloss I had entered earlier this week was not in the present ECV. A click on the ECV update button was enough to include it.
* Please update it automatically every day at noon Dutch time, which is 4am Eastern US time.

**Comment by henrinie** [comment]
Is there a reason for updating the ECV once a day instead of constructing it for each request?

**Comment by Woseseltops** [comment]
Done, in the crontab of @ocrasborn . Please leave this issue open so I can check whether it's working. Also we have to remember to change the command once we complete #190 .

**Comment by Woseseltops** [comment]
> Is there a reason for updating the ECV once a day instead of constructing it for each request?

Yes, speed :). Constructing the ECV takes about 2-5 minutes.

**Comment by henrinie** [comment]
Well that is weird. I tested ours by a request and it took 500ms to transfer it. The dataset I tested has 2158 glosses.
What could make up this kind of difference?

**Comment by Woseseltops** [comment]
It's working, closing this issue. 

> What could make up this kind of difference?

Indeed weird, we must be doing something stupid then :/ . However, since there are some more pressing issues right now, I'll leave investigation of the difference for some other time.
