### ISSUE TITLE
Add a second type of Simultaneous Morphology

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#280]
* In the second part of the morphology panel (Simultaneous Morphology), we can specify links to morphemes. Please add a possibility to also add links to other signs (much like in the panel Relations to Other Signs), under the present morpheme links. (In that way we can describe so-called 'blends', signs composed of parts of other signs, like WEEKEND which combines one hand of SATURDAY and one hand of SUNDAY)
* These sign links should also appear in the list and detail views below resp. after the Annotation ID Gloss, just like the other morphology links.

**Comment by susanodd** [comment]
@ocrasborn, just wondering, there seem to be a bunch of signs with the name pattern MOVE+ where the + is followed by the strong hand shape. (E.g., MOVE+5, MOVE+B, MOVE+O, .........)
Similarly, the pattern AT+ also appears in the same way, AT+1, AT+3, ...... with the strong hand.
Are these patterns related to anything else? Are these examples of the Blends Morphology?
I found these patterns by accident, looking at the Lemma Group AT. Then found AT+1_curved, which has strong hand 1_curved and then seems to have the same phonology as MOVE+1_curved.
Just wondering what these patterns are. Should there be a MOVE Lemma Group?
The videos of WEEKEND-A and SATURDAY, SUNDAY-B help to understand this Issue. There aren't any videos for the AT or MOVE signs.

**Comment by susanodd** [comment]
@ocrasborn, are there any additional fields you would like to have for the new Blends Simultaneous Morphology?
You mention in the Weekend example that the hands from two different signs are used.
Left Hand Sign, Right Hand Sign. Is any additional information needed?
Is the ordering of the hands significant, or is it symmetric?
SATURDAY and SUNDAY-B both have both hands the same.
Could a motion or location etc. from a third sign become part of a Blend?
Like if you'd put the SATURDAY + SUNDAY-B on top of your heart or your head?

For the current Simultaneous Morphology links, a plus sign is used to separate the sequence.
Should a different symbol be used for Blends?
(Or can the same abbreviation be used: SATURDAY + SUNDAY-B as a Blend display?)

**Comment by vanlummelhuizen** [comment]
I meant to close #224 instead of this one...

**Comment by susanodd** [comment]
@ocrasborn, in the models.py file, there are two fields in the Gloss Model with the following code:
        blend = models.CharField(_("Blend of"), max_length=100, null=True, blank=True)
        blendtf = models.NullBooleanField(_("Blend"), null=True, blank=True)
There are currently no values stored in these fields for any gloss.

**Comment by ocrasborn** [comment]
Ah, interesting. That's conceptually exactly what we are talking about here, but using these fields would not lead to links, right, as they are a CharField and a BooleanField. Could you implement something using the same type of relations as we have for the compound parts, using 'blend' in the field name(s) that are needed?

**Comment by susanodd** [comment]
@ocrasborn, what should the edit fields look like?

![edit-gloss-blend](https://user-images.githubusercontent.com/24272544/33017253-e9e37424-cdf1-11e7-823b-e4922bc76c1e.png)

**Comment by ocrasborn** [comment]
Yes! (The 'Role in this sign' is a string, right, not a vocabulary/list of field values?)

**Comment by susanodd** [comment]
Yes, I made it a string.
