### ISSUE TITLE
/dictionary/update_ecv/ also works when not logged in

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#281]
The permission 'export_ecv' is only checked when showing a button in dictionary/admin_gloss_list.html but not when requesting /dictionary/update_ecv/

This may also be the case for other permissions/urls.

**Comment by vanlummelhuizen** [comment]
OK, this wasn't a bug after all but a design choice. This url needs to be called from cronjob somewhere (once a day during the night). If it is behind a username/password the cronjob should be able to manage to do a login and get a session cookie, and use that to call this url. While this is probably feasible, it migth be better to spend time on developing a (RESTful) API of some sort that includes this url. See also #236.

**Comment by henrinie** [comment]
@vanlummelhuizen is the cronjob on the same machine as the django application? If it is, it is fairly simple to circumferenting this issue by creating a 'management command' for django. The cronjob could run that, and wouldn't need to connect to an url.

If it is on a different machine, perhaps that machine could connect to the django app machine via ssh and execute the management command.

Just my thoughts, RESTful API might be a good solution as well.
