### ISSUE TITLE
We cannot change a (specific) lemma ID-gloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#282]
When we try to change Lemma ID gloss OLIE-A to OLIE, we get an error message that's not transparent enough. As we cannot change for lemma glosses at the moment, i can't check if it already exists yet. If this is the case, please first make the error message human readable. I'll add another issue to allow searching for lemma glosses.

**Comment by vanlummelhuizen** [comment]
It failed because there was no image for OLIE-A and therefore in the update script the path to the image was None (Python's null of 'nothing' variable). The script choked on that. I fixed it by not checking for existence, while this is done later anyway.

**Comment by Woseseltops** [comment]
Done?
