### ISSUE TITLE
Add 'Added by' to search options

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#286]
Field is a reference to the user who created the gloss entry; please allow searching for the full name, rather than user name; = two fields in the database, first name - last name?

**Comment by vanlummelhuizen** [comment]
Done.

I added a Created By field in the "Search by Publication Status and Notes" panel. It checks if the search string is found in the concatenation of the first and last name of the user that created the gloss or morpheme.

**Comment by Woseseltops** [comment]
I've pulled this to the server, but I see a new empty field without a label... me or @vanlummelhuizen should have a look.

**Comment by vanlummelhuizen** [comment]
@Woseseltops I took a look at the live server and all this seems fine: 
![schermafdruk van 2017-05-15 09 19 59](https://cloud.githubusercontent.com/assets/16682631/26046583/e1d99ca4-394f-11e7-9d88-9e94c9b620d5.png)

Perhaps you forgot to restart/reload?
