### ISSUE TITLE
Enable or instruct searching by entry date

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#287]
It's not clear whether the search fields work, but any date format i can think of leads to an error. Either make it work flexibly, or present a suggested date format in grey in the search form

**Comment by vanlummelhuizen** [comment]
The error says it should match %m/%d/%y (month slash day slash year). So, e.g. 04/01/2015 should work and indeed does not immediately result in an error. While typing this the results are presented, but it is taking ages.

**Comment by vanlummelhuizen** [comment]
I implemented the quickest solution: a placeholder text (mm/dd/yyyy).

**Comment by ocrasborn** [comment]
Thanks!
