### ISSUE TITLE
Add way to expand and collapse all panels at once (detail view) 

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#289]
* Buttons with the texts 'Collapse all' and 'Expand all' would take more space than this subtle interface function would merit, but how about small icons at the right edge of every panel header (where the name is left-aligned)?
* Suggestion for icons: double arrows down [expand] and double arrows up [collapse]

**Comment by vanlummelhuizen** [comment]
An icon at the right edge of every panel would in my opinion suggest that it targets that panel only, not all panels together. Just two icons just above the first panel and that stay visible while scrolling would be clearer, I think.

**Comment by ocrasborn** [comment]
True. Let's try it out with what you suggest.

**Comment by vanlummelhuizen** [comment]
Took me quite a while, but I got it working now.
![schermafdruk van 2017-03-22 17 07 49](https://cloud.githubusercontent.com/assets/16682631/24207906/76d49a78-0f22-11e7-92fe-8b3afaa7134c.png)
![schermafdruk van 2017-03-22 17 06 31](https://cloud.githubusercontent.com/assets/16682631/24207907/76d681b2-0f22-11e7-822b-4cbd759506ea.png)

**Comment by ocrasborn** [comment]
Nice @vanlummelhuizen ! Please also copy to ASL.

**Comment by Woseseltops** [comment]
As far as I'm concerned, we can close this issue; it will appear automatically on the new American server once we get access.
