### ISSUE TITLE
Hide language fields from ASL SB

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#292]
* Hide the Dutch/Chinese language fields from the ASL admin pages
* Plus #291 !

**Comment by vanlummelhuizen** [comment]
Done for FieldChoices and Pages. If I overlooked other places, please let me know. Note that the fields are only hidden from the user. They are still in the database. That is ok, they won't harm anything.

**Comment by Woseseltops** [comment]
This will have to wait until we have the American server

**Comment by Woseseltops** [comment]
Turns out this was already working, now I know what the 'ENGLISH_ONLY' setting is for :) .  Happy, @ocrasborn ?

**Comment by Woseseltops** [comment]
(btw, @vanlummelhuizen maybe it's good to link this to your issue that makes the interface languages more dynamic, but I can't find which issue that is)
