### ISSUE TITLE
Change 'Recently added signs' for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#293]
* Make the list that is displayed with the menu item show all signs that are added in the last 7 days
* Add a menu item that shows a similar list, showing all signs that have the tag 'Proposed new sign' or for which the field Proposed new sign (panel Publication Status) is TRUE.
* [OC, note to self: check how coloring is used now, and whether that needs to be adapted]

**Comment by vanlummelhuizen** [comment]
First part is done. The list now can show Glosses (and Morphemes) added in the last X days (or hours, minutes, years, etc.). To confige Signbank to do so add something like the following to the server_specific settings:

```
import datetime
RECENTLY_ADDED_SIGNS_PERIOD = datetime.timedelta(days=7)
```

@ocrasborn the second part of your request is very similar to the situation before my changes, i.e. the Proposed new sign field was checked. So the new menu item should be doing what the old was almost doing, but only for ASL?

**Comment by ocrasborn** [comment]
Almost: the old page only displayed a selection based on the binary field "Proposed new sign"; the request is to _also_ show signs that have the tag "Sign: proposedIDgloss needs approval".

**Comment by vanlummelhuizen** [comment]
Second part also done. It is found via the following url: /signs/proposed_new/ To add this to the menu, you need to add a Page in the Django admin pointing to this url. Menu text could be "Proposed new signs" (Dutch: "Voorgesteld nieuwe gebaren", Chinese: i don't know).

((Leaning a lot about combining queries and queryset in Django :) ))

**Comment by henrinie** [comment]
@vanlummelhuizen Is the pages app needed to handle the menu links for things like this? It seems that this link should be added in the menu anyway, perhaps adding them directly into the template file would be useful? That is what I have started doing for these 'non-content pages'.

**Comment by vanlummelhuizen** [comment]
@henrinie I don't know. I just mimicked what was already there. @Woseseltops any thoughts about this?

**Comment by Woseseltops** [comment]
How we do it right now:
1. Create a page in the pages application, so it appears in the menu
2. Redirect the page to a custom view in urls.py

This is not a really pretty solution; have an alternative @henrinie ?

**Comment by henrinie** [comment]
@Woseseltops We are just listing the links directly in the template. We show links for flatpages/contentpages (same as your pages in Pages app) in the menu before other links.
https://github.com/Signbank/FinSL-signbank/blob/master/templates/menu.html#L21-L42

I decided to do it this way, because adding links to pages we want to show in the menu via the Pages app was cumbersome. We want to show those links anyway, so adding them via pages app is just one extra step.

**Comment by Woseseltops** [comment]
Added the setting for 'recently added signs', so it only shows the last 7 days, and made a new menu item for 'proposed new signs'. 

Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
Yes I am.
