### ISSUE TITLE
Allow for exclusion of some signs from the ECV

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#294]
* Add binary field 'Exclude from ECV' under Publication Status
* Exclude signs for which the value is TRUE from the ECV export (both the manual one and the automatic update -- or do these use the same routine?)
* For both ASL and NGT

**Comment by vanlummelhuizen** [comment]
Done. 
@ocrasborn When committing my stuff, I wondered whether the default when creating a new gloss should be true or false.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , good question! Please make the default 'true'.

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by ocrasborn** [comment]
Sorry, I saw it live and blindly closed it -- but it doesn't work yet! Error pop-up.

**Comment by vanlummelhuizen** [comment]
Where exactly? I just tried updating a gloss by setting 'Exclude from ECV' from No to Yes and that seems to work.

**Comment by ocrasborn** [comment]
ah! Wessel must have been in the process of integrating your code and wasn't quite done yet, as now it works fine for all test items i'm trying to leave out of the ECV.

**Comment by Woseseltops** [comment]
I indeed saw you were replying to issues exactly when I was merging the work of @vanlummelhuizen yesterday :)

**Comment by ocrasborn** [comment]
I think I made a polarity mistake, sorry for that: could you set the default to false/no? (so include in the ECV as the default)

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by Woseseltops** [comment]
Live, can this be closed @ocrasborn ?
