### ISSUE TITLE
"Edit next" button leads to error

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#295]

**Comment by vanlummelhuizen** [comment]
It is a problem similar to #279 (see https://github.com/Signbank/NGT-signbank/issues/279#issuecomment-290326898). Clicking on the button invokes a Javascript function that redirects the browser to some absolute url path. So, the path is put directly behind the hostname. The subfolder for ASL, /asl-signbank, is lost.

Unfortunately, the Javascript is not dynamically generated and so it cannot use the URL setting (the solution I used in #279).

So, I need to dig into this to come up with something.

**Comment by vanlummelhuizen** [comment]
OK, that was easy. I thought of a construction of passing the URL setting via a template to the Javascript. The Javascript variable-name 'url' was already used and exactly doing what I wanted. :)

**Comment by ocrasborn** [comment]
Works; please add to ASL as well.

**Comment by Woseseltops** [comment]
As far as I'm concerned, we can close this issue; it will appear automatically on the new American server once we get access.
