### ISSUE TITLE
Freeze header and menu bar, let rest of page scroll under it

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#298]
(for both ASL and NGT)

**Comment by henrinie** [comment]
This is very bad for  small screens.
I recommend you do a menu that hides when it is not visible, but you could open it again from the "menu hamburger" button.

**Comment by ocrasborn** [comment]
Or would it be possible to create a floating button, like you have on Whatsapp when there's a new message while you are reading something way up above? I'm not so concerned about the small screens, few people work with 13" laptops for instance, but this might be a good time to create a bit more of a condensed header and menu bar, to reduce that problem. I find the top and bottom spacing on both menu bar and panel headers rather large. Not sure if they're controlled by the same css element or something like that, but they could both be more reduced. We should create a separate issue for that, but please let's first hear your views, @Woseseltops + @vanlummelhuizen .

**Comment by Woseseltops** [comment]
Let me summarize.

Goal: have easier access to the menu bar when the pages are longer.

Proposed solutions:
* Have the whole header and menu bar always visible.
* If the menu bar is not visible, show a hamburger menu.
* If the menu bar is not visible, show an arrow that will make you scroll up instantly.

My own suggestions: 
* Instead of making both the header and the menu bar always visible, only do the menu bar.
* Only make things visible when you scroll up, like this: https://codepen.io/sunnyxyst/pen/DwgFm

I've made a separate issue for the other thing you mentioned, @ocrasborn : https://github.com/Signbank/NGT-signbank/issues/305

**Comment by henrinie** [comment]
@Woseseltops your suggestions are pretty good. The header of the site is not really needed to be shown all the time, but the menu might be needed.
But on the other hand, what parts of the menu are needed? @ocrasborn what is the part in the menu you want to be able to access all the time?
Perhaps the real issue needs to be identified, it might not be that the menu needs to be shown all the time if you need to use only of the the links in it?

**Comment by vanlummelhuizen** [comment]
@Woseseltops Bootstrap has the affix plugin (https://www.w3schools.com/Bootstrap/bootstrap_affix.asp), often used to fix menu at the top. It makes your first suggestion easy to implement. I used it for the expand/collapse all buttons in the gloss detail view.

**Comment by henrinie** [comment]
The affix plugin seems like a good solution for this issue, if you want to see the menu at all times.

**Comment by vanlummelhuizen** [comment]
I have made the menu bar fix at the top of the page when scrolling.
![schermafdruk van 2017-04-12 10 44 30](https://cloud.githubusercontent.com/assets/16682631/24949229/26e925e6-1f6d-11e7-941d-5bd7de8561f3.png)

**Comment by henrinie** [comment]
Nice work 👍
Have you tested if it will work with mobile?

**Comment by vanlummelhuizen** [comment]
The mobile site looks completely different and is not really working.
![screenshot_20170412-115945](https://cloud.githubusercontent.com/assets/16682631/24952565/27ea9f50-1f78-11e7-9ff3-98b12915ccfc.png)

When making my browser very small, it works ok.

**Comment by ocrasborn** [comment]
That's right, we've dropped support for low resolution screens from the start. We will reconsider this once we open up the public view for more signs, perhaps next year.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , this is not yet live, is it? I don't see it on Mac (Safari/Firefox) yet.

**Comment by Woseseltops** [comment]
It is live now! Very cool, signbank is starting to get really fancy with all of this javascript functionality.

**Comment by ocrasborn** [comment]
Cool indeed; please also copy to ASL, where they came up with the suggestion.

**Comment by Woseseltops** [comment]
As far as I'm concerned, we can close this issue; it will appear automatically on the new American server once we get access.
