### ISSUE TITLE
Create button to quickly scroll to top of list

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#299]
* Sometimes the list of search results (or the list of all signs) is very long, scrolling back to the top then is a bit annoying. Please create a subtle button somewhere to jump back to the top
* After #298 
* For both NGT and ASL

**Comment by henrinie** [comment]
Your keyboard has a button for this called "Home". Well at least normal keyboards, not sure about Macs!
Would that solve this issue?

**Comment by ocrasborn** [comment]
Yes, I know. Some mac keyboards have that button, many don't. Laptops don't, for instance. This is why the issue came up.

**Comment by henrinie** [comment]
It seems that the End&Home button might be available in Macbooks, at least according to this page: http://osxdaily.com/2015/06/17/home-end-button-mac-keyboard-functions/

**Comment by ocrasborn** [comment]
Ah, thanks @henrinie -- one learns something every day. So simple. Let's just drop this issue, I suggest, while still maintaining the related ones about the header.
