### ISSUE TITLE
Remove morpheme search for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#300]
The Search button below the search form is a pull-down menu for NGT, allowing the user to choose whether to search signs or morphemes or both. As the ASL Signbank doesn't have the morpheme functionality, please remove the morpheme options there and put back a simple Search signs button.

**Comment by vanlummelhuizen** [comment]
To let Signbank show the morpheme search in the pull down menu, add `SHOW_MORPHEME_SEARCH = True` to settings/base.py.

**Comment by Woseseltops** [comment]
Something that will be done once we get access to the American server; removed top priority for now.

**Comment by Woseseltops** [comment]
Working my way through the 'tbc after asl migration' issues. I think the ASL SB has this now, agree this can be closed @ocrasborn ?
