### ISSUE TITLE
Name video files after annotation_idgloss instead of idgloss

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#306]
As annotation_idgloss is unique, while idgloss is not.

**Comment by vanlummelhuizen** [comment]
I found two places in the code to change:

1. function import_media in dictionary/views.py (when batch inporting videos)
2. function addvideo in video/views.py (when uploading a video for a gloss)

Then there is the procedure of updating the video file names to the annotation_idgloss.

Is this complete and correct, @Woseseltops and @ocrasborn ?

**Comment by Woseseltops** [comment]
I would say the main place is https://github.com/Signbank/NGT-signbank/blob/master/signbank/dictionary/models.py#L585 , which is the code that tries to guess the video path/filename based on the (currently) idgloss.

**Comment by henrinie** [comment]
It might be a good idea to have only one place that defines how the file name is constructed, if there are several there is always more room for error.
By the way, are you in some way dependent of the file names being correctly named? Do you have some scripting that works on the video files?

**Comment by Woseseltops** [comment]
Discussed this one with Micha; as annotation_idgloss will be replaced by a more dynamic multi-lingual system, this issue no longer makes sense. Close if you agree, @ocrasborn

**Comment by ocrasborn** [comment]
I don't agree (it's unrelated; the point is that the movies are linked to unique glosses, where Lemma ID Glosses can re-occur for multiple movies/annotation glosses.
We agreed that we'll close this for now, as the file names of the movies remain unique as they are combinations of gloss + id number.
