### ISSUE TITLE
Cannot add Relation to other sign anymore

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#307]
IntegrityError at /dictionary/update/relation/
NOT NULL constraint failed: reversion_revision.manager_slug
Request Method:	POST
Request URL:	https://signbank.science.ru.nl/dictionary/update/relation/
Django Version:	1.11
Exception Type:	IntegrityError
Exception Value:	
NOT NULL constraint failed: reversion_revision.manager_slug
Exception Location:	/scratch2/www/signbank/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py in execute, line 328
Python Executable:	/usr/bin/uwsgi-core
Python Version:	3.4.3
Python Path:	
['.',
 '',
 '/scratch2/www/signbank/lib/python3.4',
 '/scratch2/www/signbank/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/signbank/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/signbank/lib/python3.4/site-packages']
Server time:	Wed, 19 Apr 2017 16:38:28 +0200
Traceback Switch to copy-and-paste view

/scratch2/www/signbank/lib/python3.4/site-packages/django/db/backends/utils.py in execute
                return self.cursor.execute(sql, params) ...
▼ Local vars
Variable	Value
params	
['2017-04-19 14:38:28.878112', 2, '']
self	
<django.db.backends.utils.CursorDebugWrapper object at 0x2b31bbecea20>
sql	
('INSERT INTO "reversion_revision" ("date_created", "user_id", "comment") '
 'VALUES (%s, %s, %s)')
/scratch2/www/signbank/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py in execute
        return Database.Cursor.execute(self, query, params) ...
▼ Local vars
Variable	Value
params	
['2017-04-19 14:38:28.878112', 2, '']
query	
('INSERT INTO "reversion_revision" ("date_created", "user_id", "comment") '
 'VALUES (?, ?, ?)')
self	
<django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x2b31bbecf9d8>

**Comment by Woseseltops** [comment]
It's not just relations, I think it's everything that requires a database write action. I think this is because I didn't do yet:

> chnage the database structure of the reversion-columns manually, so they match the ones I got from updating a my test database step by step alongside Django.

I did so now. I think that fixes it, right?

**Comment by ocrasborn** [comment]
works again! thanks
