### ISSUE TITLE
Fix the automated NGT-database backups

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#308]
The backup cronjob is still backing up the Spitfire database, but since #154 NGT Signbank lives on Appleajck

**Comment by ocrasborn** [comment]
And how about the other scripts relating to the SVN repository, for updating frequency data and for the ECV stuff? @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
The frequency updating script is fixed/updated for Python3, see also #283. 
I don't know about the cronjobs.

**Comment by Woseseltops** [comment]
I changed the backup command, **it still needs to be verified whether this worked**.

**Comment by Woseseltops** [comment]
> And how about the other scripts relating to the SVN repository, for updating frequency data and for the ECV stuff?

I still need to get these working again, good point.

**Comment by Woseseltops** [comment]
Turns out the backup script was still backing up the old location because of some behaviour I was not aware of. I think I fixed it now, but let's keep this issue open so I don't forget to check.

**Comment by Woseseltops** [comment]
It's working!
