### ISSUE TITLE
Allow for searching using regular expressions

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#31]
• Esp. for Gloss and Keyword (Translation equivalent) fields (but useful for any text field)
• Is there a disadvantage to having regular expressions by default? An advantage to a checkbox switching it on/off?

**Comment by Woseseltops** [comment]
Are you sure you want this :)? 

![](http://imgs.xkcd.com/comics/perl_problems.png)

> Is there a disadvantage to having regular expressions by default?

Not really unless you want to search for special characters. For example, I see some signs using the plus sign, which has a meaning in regex, but I'm not sure how often that's used. Do you think the loss of the ability to search for a plus sign outweighs the gains of being able to use regex?

**Comment by ocrasborn** [comment]
Isn't it possible to escape the plus character using \+?

**Comment by ocrasborn** [comment]
Yes, I think I'm sure.

**Comment by Woseseltops** [comment]
> Isn't it possible to escape the plus character using +?

Sorry, what I meant with 'the loss of the ability to search for a plus sign' was the ability to do so without escaping it, because this way every user Signbank user has to be aware of regex basic, otherwise they won't understand some results.

> Yes, I think I'm sure.

Haha okay. I switched the main search field to regex to see how that goes. If we get no team members with torches and pitchforks, I'll switch over all other text fields as well.

**Comment by ocrasborn** [comment]
Main = Dutch gloss?

**Comment by Woseseltops** [comment]
Yes.

**Comment by ocrasborn** [comment]
Played around with it and instructed others; please apply to all other text fields, @Woseseltops

**Comment by henrinie** [comment]
I would be curious to know why would you change the search to support regex?
I am here with @Woseseltops - most users will not know how to use regex, therefore it ruins the whole search function for most of the users. They will no longer be able to understand what they are doing.

What are you really trying to achieve with this?

**Comment by ocrasborn** [comment]
@henrinie : our users are researchers, not lay users of a dictionary. We want much more flexibility in the search, and always "starts with" or always "substring match" is much too limited.

**Comment by henrinie** [comment]
Ok.
So what do you need this flexibility for? What kind of patterns do you need to search for? What are you accomplishing with these patterns?

**Comment by Woseseltops** [comment]
Okay, switched all main search fields to regex, for both glosses and morphemes. There are also some text search fields inside the collapsed panels, but these would require some more work to move to regex, which I estimated is not worth the effort... but do you agree @ocrasborn ?

**Comment by ocrasborn** [comment]
Not sure; but let's see in time how convenient the regex are for the fields where we can use them now, and how much we will miss the option for the other fields. I'll close this for now.

**Comment by ocrasborn** [comment]
@henrinie : some examples:
[#*]
VINDEN|ZOEKEN
ing$
