### ISSUE TITLE
Gloss doesn't appear correctly in search results

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#310]
Not sure if this is an entry-specific problem, but gloss UITBREIDEN-B appears as UITBREIDEN in the list view and in the horizontal search result bar.

**Comment by Woseseltops** [comment]
You mean this gloss? https://signbank.science.ru.nl//dictionary/gloss/3417/ Because that one is called 'UITBREIDEN-B' everywhere for me.

**Comment by ocrasborn** [comment]
Hm. I'm pretty sure I checked properly, but can't find a problem anymore now. Good :-)
