### ISSUE TITLE
Cannot enter new users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#313]
![screenshot 2017-04-26 14 55 38](https://cloud.githubusercontent.com/assets/10242207/25435502/80f0cfc0-2a90-11e7-949f-faf5893467e7.png)

**Comment by Woseseltops** [comment]
I think this is fixed now, problem with the (not doing of a) database upgrade.

**Comment by ocrasborn** [comment]
Works! Thanks @Woseseltops
