### ISSUE TITLE
Move the tags to higher up in the detail view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#317]
* We often miss that there are already tags present while discussing new signs. Please move the tags themselves to right above the Lemma ID Gloss field in the detail view, below the line.
* The larger header "Tags" can simply be deleted, it's clear what they are from their visual appearance.

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by Woseseltops** [comment]
Works on the NGT Signbank, can we close this?

**Comment by ocrasborn** [comment]
Nice!
