### ISSUE TITLE
Add functionality for importing translation equivalents from Excel/CSV

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#318]
Check for duplicates.

**Comment by ocrasborn** [comment]
Actually, this might already be covered by "CSV import" (menu item), but not sure whether that caters for lists of values like in this case.

**Comment by vanlummelhuizen** [comment]
I took a look at "CSV import" and it seems possible to use it if the last two columns the Excel with new translation equivalents are changed to one Keywords column which holds the new list of translations.

I will run some experiments.

**Comment by vanlummelhuizen** [comment]
Some parts of the CSV import were not yet Python 3 compatible. I changed it and now I hit a problem for which @Woseseltops probably has the answer.

@ocrasborn we are probably able to use the existing CSV import, but in order to use it, the current Excels with new translation equivalents will need some work.

**Comment by vanlummelhuizen** [comment]
@ocrasborn was this one solved?

**Comment by ocrasborn** [comment]
Yes, it works! Thanks. But now we're at it, I added #326 :-)
