### ISSUE TITLE
New phonology field values disappear after editing is disabled.

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#319]
This happens in the gloss detail view. If a phonology field is empty and is editing to contain a value, the value is not shown when the button for disabling editing is clicked. It reappears if you reload the page.

**Comment by ocrasborn** [comment]
Yes, I noticed as well. Didn't think it urgent enough to create an issue, but it's good that you did @vanlummelhuizen , we'll need to fix it at some point.

**Comment by susanodd** [comment]
I fixed this in my branch.

**Comment by susanodd** [comment]
This bug has been fixed. This works in the on-line version too now.
