### ISSUE TITLE
Search page slow

### ISSUE THREAD

**Issue by henrinie** [Signbank/NGT-signbank#322]
Hi,
I tried to have a look at NGT signbank, and it seems that your search page is extremely slow, at least when searching for "all glosses".
It takes a lot of time to load the page, in fact I didn't even manage to do it fully before my browser crashed. It makes thousands of requests to download image files, seems that after a minute of loading the page I had downloaded 382MB of data from the page.

I also noticed that some image files are exceptionally large, for example SENSEO-I-3663.png (will not post direct links in here) is 2MB in size, so is SENSEO-H-3141.png. Afaik png files can get pretty large if they are not somehow optimized.

Perhaps it would be a good idea to not download all these images on the search page, but instead provide the links to them, and load them and show them in a tooltip for example when you hover over the gloss link.

**Comment by ocrasborn** [comment]
yes
