### ISSUE TITLE
Add help pop-up for CSV import

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#324]
On https://signbank.science.ru.nl//signs/import_csv/, please add a question-mark-hover-pop-up-windowlet that says something like this:
"CSV files should have min. two columns, the first being the ID number of the sign (obtained through CSV export), the second column the value that needs to be put in the field. Make sure the header row is cf. the CSV export, indicating the fields you want to make changes to. In case of adding new values to comma-separated fields like Translation Equivalents, make sure that the old values that should stay are also in the second column."

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by ocrasborn** [comment]
Nice, thanks. One minor request: as a general style rule, let's always put these question marks to the right of a line of text. In this case, please move it to the end of the first line.

**Comment by vanlummelhuizen** [comment]
OK. Heads up: it may take some time because the (small) form is automatically generated and inserting something in the generated part could be tricky.

**Comment by ocrasborn** [comment]
I see. Should you be able to fix it in 10 minutes then good, if not, let's drop it. But stick to the general rule everywhere else :-)

**Comment by vanlummelhuizen** [comment]
OK, looked at it for a little more than 10 min. I think I was on the right track, but it would take more time. It seems the Django documentation is not clear.

In case someone is revisiting this:
https://docs.djangoproject.com/en/1.11/ref/forms/renderers/ (bottom)
https://github.com/pydanny/django-widget-override-test-case
https://code.djangoproject.com/ticket/28088

**Comment by ocrasborn** [comment]
Maybe part of the problem is that the whole layout of this page is rather messy. Four short lines/rows are crammed together, and then most of the page is empty. Would it be an alternative to double the line space as it were, here? That would make the question mark more visible as well.

**Comment by vanlummelhuizen** [comment]
@ocrasborn what do you this of this? I have tried to make the tooltip wider, but haven't succeeded so far.
![schermafdruk van 2017-05-31 11 33 08](https://cloud.githubusercontent.com/assets/16682631/26625682/23de4f26-45f5-11e7-98fe-7b30ee41b9bf.png)

**Comment by ocrasborn** [comment]
Yes, much better!

**Comment by vanlummelhuizen** [comment]
Done.

**Comment by vanlummelhuizen** [comment]
Note to who ever revisits this issue. The Javascript used for this came from http://markusslima.github.io/bootstrap-filestyle/

**Comment by Woseseltops** [comment]
Live, can this be closed?
