### ISSUE TITLE
Add hyperlinks for compound parts in Annotation ID Gloss: English (list view) 

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#329]

**Comment by susanodd** [comment]
@ocrasborn, it looks like this is working. If you search on METAAL then you see the gloss METAALOPLEIDING, where the English METALLURGY-TRAINING has the two components below it, METAL + TRAINING.

**Comment by ocrasborn** [comment]
That's right, but the issue is to make these two component parts hyperlinked to the constituting signs, just like they are below the Dutch Annotation ID Gloss in the list view, and just like the English ones in the detail view.

**Comment by susanodd** [comment]
This has been fixed.
