### ISSUE TITLE
Add fields 'weak drop' and 'weak prop'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#334]
* These are phonology fields with three values (none, yes, no), and are a specification of the information in 'handedness'.
* It would be nice if in the detail view we could display them in connection with the field handedness, ideally on the same line, so that we get a bit of a more compact view. The field labels could be abbreviated to "WD" and "WP" to make this possible. If this doesn't work out, put them immediately below handedness.
* Also enable searching for this iformation.

**Comment by ocrasborn** [comment]
Oh, for the non-sign linguist: these refer to the possibility of articulating two-handed signs with one hand (weak drop) or vice versa (weak prop).

**Comment by susanodd** [comment]
Do you want to be able to explicitly set a value to None?
This is the initial value when the field has never been set.
Once you start setting and unsetting a checkbox, then in the database it gets set to 1 or 0.
The repeat and altern fields are also like this.

**Comment by ocrasborn** [comment]
Let's make it so that they show the same behaviour as the repeat/altern fields.

**Comment by susanodd** [comment]
Okay, I just pushed it to the github.
It's available in Gloss Detail View. I made it so it looks like what you describe first, that the WD, WP are on the same line after the Handedness. They only show up when set. You can set the checkbox when in edit mode. If they're not set they're invisible. (You can click to edit under the heading WD or WP.)

**Comment by vanlummelhuizen** [comment]
@ocrasborn This is live now.

**Comment by ocrasborn** [comment]
On Mac/Safari, I only see the field labels, but no checkboxes 

![screenshot 2017-09-04 12 52 49](https://user-images.githubusercontent.com/10242207/30023513-09e60ff2-9170-11e7-967d-59b673c2e0e5.png)

**Comment by susanodd** [comment]
Click in the white space. :)
(I'll adjust it.)

**Comment by susanodd** [comment]
Okay, I fixed the formatting. Now it shows the same ------ as the other fields.
Querying has been added.

**Comment by susanodd** [comment]
@ocrasborn, @vanlummelhuizen put this on the live server.

**Comment by ocrasborn** [comment]
(See #371 for the nature of the values, I messed up my comments. These two fields WD/WP is where we need to distinguish between neutral/yes/no; for the number/letter etymology the checkbox in the interface is best).
