### ISSUE TITLE
Deleting videos from the detail view doesn't work anymore

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#336]
Deleting images seems to work well, still.

**Comment by Woseseltops** [comment]
Do you have some more specific info for me on what you were doing? I just deleted 10 videos (fake signs :P) , and it worked perfectly.

**Comment by ocrasborn** [comment]
I searched for tag 'Video: wrong sign', and tried to delete a few. What happens is that after clicking the button, the edit mode switches off and the video is still there. Feel free to try for any sign with this tag.

**Comment by ocrasborn** [comment]
Rebooting today didn't solve it, I still can't delete any of the videos for signs tagged 'video: wrong sign'. Also, Anique noticed it on a PC first, this time it's not a mac thingy ;-)

**Comment by Woseseltops** [comment]
Fixed it! Turned out that some videos were saved a bit different than others, perhaps some were uploaded in bulk? Anyway, videos are now deleted the proper way that works everytime.

> Feel free to try for any sign with this tag.

Made local backup saves to be sure.

**Comment by ocrasborn** [comment]
Thanks @Woseseltops ! Works well now indeed.
