### ISSUE TITLE
Allow user to set a default data set (for display and searching)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#341]
* That is, iff the user has access to multiple datasets. Otherwise this option can be hidden or greyed out.
* If we wouldn't somehow let the user control this, s/he would have to select a dataset every time before performing a query. If by contrast there is a default data set specified by the admin in Django (or if the system simply selects a default dataset by alphabetical order), then we'd limit the flexibility of working with multiple datasets (and likewise frustrate the users).
* With these type of per-user settings, it starts to make sense to have a preferences/settings/account info page, where various display options can be configured (in the future), and some user stats can be shown (in the future; like: list of datasets the user has access to; preferred interface language; last login date; number of entries added per dataset; number of entries edited per dataset; ...)

**Comment by henrinie** [comment]
I figured that this might be a non-issue, at least for us. In finsl you can
search from all the datasets you have permissions to, so the search shows
results for all those datasets, unless the user selects one.

Currently most normal users only have access to one dataset. You might want
to analyze your situation, and consider if you really need this
functionality before implementing it.

16.6.2017 15.15 "ocrasborn" <notifications@github.com> kirjoitti:

**Comment by ocrasborn** [comment]
This has been addressed by #225 and #230 , so I'm closing this.
