### ISSUE TITLE
Public view sometimes cannot be activated

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#342]
Please check the bug here, the Public View does not work.
https://signbank.science.ru.nl//dictionary/gloss/85/
This is an example of a sign where the Lemma is different than the Dutch field.
(I am trying to find out where this bug arises, it seems the Public view is generated automatically, but it seems not to work for any of the OPEN, OPEN-C, OPEN-A signs)

**Comment by susanodd** [comment]
I fixed this.

**Comment by susanodd** [comment]
This is fixed again. Somehow the previous change never got live.
@vanlummelhuizen just pushed it to the live server.
