### ISSUE TITLE
Cannot edit Morphemes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#343]
Clicking edit button does not enable edit mode

**Comment by susanodd** [comment]
I will look at this too to see whether I did something to it. There is a javascript file that is shared by both Gloss Detail and Morpheme Detail.

**Comment by susanodd** [comment]
Easiest would be to make a new file called morpheme_edit.js that is the previous version of gloss_edit.js.
At the moment, Morpheme Detail View also uses gloss_edit.js.
Gloss Detail View has some extra html tags (for database calls) so the page isn't reloaded during editing.

**Comment by susanodd** [comment]
They probably can't share the edit enable routine anymore.

**Comment by susanodd** [comment]
Okay, I found the bug and I fixed it.

**Comment by Woseseltops** [comment]
This was already put in production last Friday. I can indeed click the edit button on a morpheme page again. Can be closed @ocrasborn ?

**Comment by Woseseltops** [comment]
PS well done @susanodd :)
