### ISSUE TITLE
Hitting enter in a text field in the Morpheme search form leads to a CSV download

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#344]
...rather than starting the query.

**Comment by ocrasborn** [comment]
We fixed this before: #250

**Comment by Woseseltops** [comment]
Hmm, I saw this at your screen, but on my machine I can't reproduce it, @ocrasborn . Has it by any chance also magically been solved for you?

**Comment by ocrasborn** [comment]
Nope. Checked again, happens not only in Safari but also in Chrome and Firefox on mac. Maybe a mac-thingy @vanlummelhuizen can check out on his test machine.

**Comment by vanlummelhuizen** [comment]
Done. I also fixed a minor thing where hitting the Reset button made the empty form to submit anyway.

**Comment by vanlummelhuizen** [comment]
This is now live by the way.

**Comment by ocrasborn** [comment]
:-)
