### ISSUE TITLE
Handshapes: add detail view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#347]
* Create a detail view with edit option for editing all handshape features

**Comment by susanodd** [comment]
![handshape_with_image](https://user-images.githubusercontent.com/24272544/27958271-90dee1ae-6322-11e7-82ca-5541e301ea07.png)
![handshape_view_edit](https://user-images.githubusercontent.com/24272544/27958282-9952e2b8-6322-11e7-8a4a-9e8631531321.png)

**Comment by susanodd** [comment]
![handshape-detail-view](https://user-images.githubusercontent.com/24272544/28275352-e4613392-6b13-11e7-9134-ff2445ec65d4.png)

**Comment by susanodd** [comment]
![handshape-detail-view-edit](https://user-images.githubusercontent.com/24272544/28275373-f1e11492-6b13-11e7-8986-62b3293224c8.png)

**Comment by ocrasborn** [comment]
Looks good! One request: to leave the finger Selection and Finger Configuration "1" unnumbered, and consistently add "2" as a suffix for the second pair; in the screen shots it's a bit mixed.

**Comment by susanodd** [comment]
https://signbank.science.ru.nl//dictionary/handshape/4/
https://signbank.science.ru.nl//dictionary/handshape/29/
https://signbank.science.ru.nl//dictionary/handshape/80/

**Comment by ocrasborn** [comment]
@susanodd , could you move the field "Finger configuration 2" down, to be below "Finger selection 2"?

**Comment by susanodd** [comment]
Fixed. (Pushed to github master branch.)
