### ISSUE TITLE
Reduce amount of white space in panel Relations to Other Signs (Detail view)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#356]
* Whether there is one or multiple or no related sign specified, there is always unnecessary white space at the bottom; please make more condense, like in the other panels.
* ah, in fact this holds for all panels (Morphology, Relations to Foreign Signs) where relations can be specified, so please alter everywhere.

**Comment by susanodd** [comment]
Fixed. (Pushed to github master.)
