### ISSUE TITLE
Reverse columns for displaying simultaneous morphemes in a gloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#361]
The fields when editing are in the correct order, and it is saved correctly, but the headers and the saved data are in the reverse order. Please make everything like this: first Morpheme gloss, then Meaning in this sign.

![screenshot 2017-07-31 14 58 23](https://user-images.githubusercontent.com/10242207/28778801-23b3f29e-7601-11e7-9974-453bf341ca0c.png)

**Comment by susanodd** [comment]
Fixed. (Pushed to github master branch.)
