### ISSUE TITLE
Add menu item 'Search handshape' under 'Signs'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#365]
...and put it below "Search morpheme"
(I can add the menu text myself, but I cannot link it to https://signbank.science.ru.nl/dictionary/handshapes/, hence the request)

**Comment by Woseseltops** [comment]
Done. Happy, @ocrasborn ?

**Comment by ocrasborn** [comment]
Could you still hide the menu item for anonymous users, @Woseseltops ?

**Comment by Woseseltops** [comment]
Of course, done.
