### ISSUE TITLE
Search hits bar doesn't work for handshapes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#374]
![screenshot 2017-09-04 13 14 23](https://user-images.githubusercontent.com/10242207/30024231-17829e5c-9173-11e7-9d7e-536b3af9c5ac.png)

**Comment by ocrasborn** [comment]
I get this view in the screenshot if I click on a handshape value in a sign (whether in Detail View or List View). If I actually search for handshape, the bar doesn't appear at all. It'd be useful to have this bar for all handshape results, it allows for quick jumping from handshape to handshape, just like for signs.

**Comment by susanodd** [comment]
Yes, I notced that. It has to do with how the previous search results are cached. (In a session variable.)
It probably needs a "search type" to also be cached in order to allow to check if the previous search results are still the correct type.

**Comment by susanodd** [comment]
Okay, I fixed this. Pushed to github master branch.

**Comment by vanlummelhuizen** [comment]
@ocrasborn @susanodd This is live now.

**Comment by ocrasborn** [comment]
But now it's gone altogether, right? Would it be possible to create a working version so that we can jump from handshape to handshape quickly?

**Comment by susanodd** [comment]
It shows the most recent query, if the most recent query was handshapes.
Try querying handshapes, then selecting one of the results.
I will adjust it so that if there isn't a recent handshapes query, it shows all handshapes.
