### ISSUE TITLE
Error upon trying to delete field choice

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#376]
I get a 'TypeError' when I try to delete a field choice (for JointConfiguration). And also one when I click on a field value to edit it (which definitively was possible before). Please repair.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Ok, apparently a change I made for the upgrade to Python 3 (__unicode__ to __str__) did not work for FieldChoice. I changed it back. It seems to work again.

**Comment by ocrasborn** [comment]
Positive! Thanks @vanlummelhuizen
