### ISSUE TITLE
Header columns in CSV export get capital letters

### ISSUE THREAD

**Issue by susanodd** [Signbank/NGT-signbank#377]
This seems to be a bug. When you export a CSV file, the Headers end up with capital letters on words like "of" and "in". This causes a problem when you later want to import that file, because the verbose Model names no longer match the exported verbose column names.
E.g., 'Number Of Occurrences In Amsterdam' (CSV) is not the same as 'Number of Occurrences in Amsterdam' (Model).
This causes some of the data to be imported to be ignored. Like all of the Frequency data because all of those columns have "Of" in the exported header, but "of" in the Model.

**Comment by ocrasborn** [comment]
Ah, it'd be good to repair that. But like i said before, we won't ever be importing frequencies, so if it's just for those columns, don't bother fixing this right now.

**Comment by susanodd** [comment]
This has been fixed.
