### ISSUE TITLE
Cannot edit the boolean fields 'altern' (Alternating Movement) and 'repeat' (Repeated movement)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#38]
...and while we're add it: could you change the display values 'true' and 'false' to 'yes' and 'no'?

**Comment by Woseseltops** [comment]
Pfff, this one was well hidden, but I eventually found the problem and fixed it. The 'yes/no' thing was a different place in the code, but I fixed that part as well.

**Comment by ocrasborn** [comment]
This is broken again after the updates...

**Comment by vanlummelhuizen** [comment]
The fix was easy. I'll assign it to @Woseseltops.

**Comment by Woseseltops** [comment]
Live, can be closed @ocrasborn ?

**Comment by ocrasborn** [comment]
I have to reopen this, it appears broken again. The following error pops up when I click "OK" to confirm my checking the checkbox:

There was an error processing this change: UnboundLocalError at /dictionary/update/gloss/4603
local variable 'category_value' referenced before assignment

Request Method: POST
Request URL: https://signbank.science.ru.nl/dictionary/update/gloss/4603
Django Version: 1.11
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.4.3
Python Path: ['.', '', '/scratch2/www/signbank/lib/python3.4', '/scratch2/www/signbank/lib/python3.4/plat-x86_64-linux-gnu', '/scratch2/www/signbank/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/scratch2/www/signbank/lib/python3.4/site-packages']
Server time: Thu, 15 Jun 2017 17:39:45 +0200

**Comment by ocrasborn** [comment]
Same or similar problem with the three binary (checkmarks in interface) fields in the panel Publication Status.

**Comment by Woseseltops** [comment]
Picked up this one after email by Inge indicating this was blocking.

Found 3 problems preventing this from working:
* The category_value variable could be undefined
* Setting the booleans to true was not recognized in all cases
* A new 'exclude from CSV' property was not configured yet.

Weird, I don't understand why this worked before (these problems were not introduced recently), but I think it's fixed now.
