### ISSUE TITLE
Error in gloss blocks many functions

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#380]
There is a problem opening a test gloss (we can't find back which, wessel_test3 comes closest to our memory), and now 'search gloss containing we' for instance leads to an error.
We have been deleting many handshape values that were no longer in use, perhaps that is related.
Wasn't able to delete the gloss in the admin either.

**Comment by Woseseltops** [comment]
Ha, interesting bug. After some investigation, I discovered that wesseltest3 was still using a fieldchoice (of type 'handshape') that was deleted. Once I changed some phonology settings, everything seems normal again. You can safely search for 'wes' again :)

Maybe we want to create an issue that somehow checks whether a fieldchoice is in use before it's deleted in the admin?

**Comment by ocrasborn** [comment]
thanks Wessel; I'll add that issue, good idea
