### ISSUE TITLE
CSV export of morphemes is broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#382]
* "'Morpheme' object has no attribute 'language'"

**Comment by susanodd** [comment]
Hi, the error is a line in dictionary file adminviews.py:

signlanguages = [signlanguage.name for signlanguage in gloss.language.all()]

should be:

signlanguages = [signlanguage.name for signlanguage in gloss.signlanguage.all()]

(Updated on my local version fixes the issue.)

I looked through the archive and it looks like this code -- field language -- has been this way for a very long time (perhaps always).
Perhaps the Gloss field signlanguage used to be language.

**Comment by ocrasborn** [comment]
Ah thanks. Yes, I think it was 'language', @vanlummelhuizen recently changed it.

**Comment by ocrasborn** [comment]
Works.
