### ISSUE TITLE
Hide the Dataset column from the ASL SB list template

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#393]
(It's not relevant to ASL SB for now.)

**Comment by Woseseltops** [comment]
Added option to hide dataset features; once this option reaches the ASL Sigbank (in about 3 weeks), it will automatically hide the dataset column in the list view. Any other things you want to use this option for, @ocrasborn ? Two ideas:
* The dataset information in the detail view
* #397

**Comment by Woseseltops** [comment]
Did the first option, but not the second, because it turns out that depends on the general template... which is different for ASL anyway (so the list of datasets would not have been shown to them anyway) :) . Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
yes!
