### ISSUE TITLE
Add an 'end date' for users in Django

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#40]
In the Users page in Django, there is a panel 'Important dates'. Add a way to specify the expiry date of an account here (meaning the date on which access will be blocked; the account specification can stay in the db)

**Comment by ocrasborn** [comment]
See also #106

**Comment by Woseseltops** [comment]
Done! Added to the model, migrated the database, and added a check at login; expiry dates should not be in the past. If it is, you get sent back to the login screen.

**Comment by Woseseltops** [comment]
PS Do we want to add this as a column to the user list in the django admin as well?

**Comment by ocrasborn** [comment]
Yes, please.

**Comment by Woseseltops** [comment]
Done
