### ISSUE TITLE
Stop SB from reloading after selecting the current interface language

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#404]
* After selecting the interface language that is already selected, SB keeps reloading. We should somehow prevent this from happening: either by showing only the non-active languages in the menu (but then the flag for the current language would need to change to something like 'Select other language'), or by actually solving the 'bug'.
* Alternative: see how it is done in FinSL Signbank?

**Comment by susanodd** [comment]
This has been pushed to github.
