### ISSUE TITLE
Improve site header

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#62]
• picture files and red background are two different colours
• doesn't resize OK
• logo should be more to the right (say 25px from the right margin of the red box

**Comment by Woseseltops** [comment]
> picture files and red background are two different colours

I must misunderstand what you mean here. I made a screenshot, and I get the color #b82b22 for all red pixels I tried, whether close or very far from any logo.

**Comment by Woseseltops** [comment]
> logo should be more to the right (say 25px from the right margin of the red box

I've moved the logo to a more logical place now.

**Comment by richardbank** [comment]
>I made a screenshot, and I get the color #b82b22 for all red pixels I tried, whether close or very far from any logo.

This may well be a browser thing, different render engines may render different colours of logos. Looks OK to me on Chrome, IE and FF on WIN8.1

**Comment by ocrasborn** [comment]
I also made a screen shot, see below, to illustrate the second problem in the issue which is still there: resizing the window becomes a problem if it gets too narrow.
![screenshot 2016-01-27 15 40 09](https://cloud.githubusercontent.com/assets/10242207/12616630/71087346-c50c-11e5-9587-fc7c24f8edb5.png)

**Comment by Woseseltops** [comment]
Indeed, I hadn't looked at that one yet. It's fixed now. Surprisingly, it was the textual logo which was very long.

**Comment by ocrasborn** [comment]
I don't see any colour problems on Safari anymore either.
