### ISSUE TITLE
Allow for importing of new glosses by the user

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#79]
Create an import function somewhere where the user can upload a CSV file that contains ID Gloss, Annotation ID Gloss, and Annotation ID Gloss English in three columns, creating new signs on the basis of those three values. Give feedback about which glosses were correctly created and which glosses already existed (on the basis of Annotation ID Gloss and/or Annotation ID Gloss English).

**Comment by susanodd** [comment]
![excel-create-new-glosses](https://user-images.githubusercontent.com/24272544/31080360-c19f3dca-a788-11e7-8c72-67611653940f.png)
![feedback-import-csv-create-glosses](https://user-images.githubusercontent.com/24272544/31080371-c6e2cb12-a788-11e7-951c-710c7e72b564.png)

**Comment by susanodd** [comment]
I have it so it checks for the existance of the Annotation ID Gloss: Dutch.
If that's found, it's listed as Already Existing.
If it's not found, it's listed under To Create.
(I haven't done the actual creation yet, first checking the layout here. Should there be a button?)

I'm not sure what to do with a case where the Dutch doesn't exist, but an English one does?
What would the Dutch one look like in this case? Empty?
If it's not empty but not found, then that seems more like an update of the English gloss?

**Comment by ocrasborn** [comment]
It would be good to split out the 'already existing' in three groups:
1. Already existing Annotation ID Glosses in both Dutch and English
2. Already existing Annotation ID Glosses in Dutch
3. Already existing Annotation ID Glosses in English
And indeed, then a button at the end "Create glosses" should create the ones that have non-existing values for both Dutch/English.
Note: 'Dutch' should actually be a variable: it depends on the description language of the dataset; please check with @vanlummelhuizen

**Comment by susanodd** [comment]
One question, what happens if the already existing Dutch or English glosses are not fields in the same gloss? Can this happen? Should there be a fourth case for when they are both already existing but are different glosses? (I guess that could happen if they were entered separately.)

**Comment by susanodd** [comment]
![import-glosses-spreadsheet](https://user-images.githubusercontent.com/24272544/31128442-1da613d6-a852-11e7-8402-2e8fb9672a47.png)
![import-csv-feedback](https://user-images.githubusercontent.com/24272544/31128445-2165e6f4-a852-11e7-89c6-0ee351a35c80.png)

**Comment by susanodd** [comment]
The above example is meant to be weird (bad) data, in order to test the import function.
Should there be an error message if the user "splits" the fields across more than one gloss? (e.g., the case where the row to import has Annotation ID Gloss fields belonging to more than one gloss already in the database, but not the same gloss.)
(I can't really tell if this is something people would try to do or not. But perhpas it could happen if somebody really wants to make relations between glosses and tries to do it this way.)

**Comment by susanodd** [comment]
![import-csv-create-glosses](https://user-images.githubusercontent.com/24272544/31230164-81de73ce-a9e3-11e7-92a5-99f0eec2f654.png)

**Comment by susanodd** [comment]
This has been pushed to github. The red text is links to the already existing glosses. The creation is not done yet.

**Comment by ocrasborn** [comment]
Tested it so far: works for me. Unlike what I see in your screen shot above, the column "Dataset Glosses" is now obligatory, right? If I leave it out, I get an error. (Which is good, it should be obligatory from now on.)
One request: to change the column header "Dataset Glosses" to simply "Dataset".

**Comment by susanodd** [comment]
Okay, this is fixed now. I added some additional error checking so that if insufficient columns are present or the column names are wrong that an error message is included in the feedback.
I tried printing out a list of possible columns but that is too long, so I made it be a message to tell the user to first try exporting to check what column names are possible.

**Comment by susanodd** [comment]
Okay, this is ready now. There is a new button to create the new glosses  (Visible when the section Glosses to Create has data.)

**Comment by ocrasborn** [comment]
Great @susanodd ! One request and potential problem: glosses should be unique _within_ datasets, but need not be unique _between_ datasets. (Spoken analogy: I should be able to enter the form 'bank' in both English and Dutch, even though they may mean different things.) Can we incorporate that just here, or does the Gloss model also need to be changed because uniqueness is specified there? @Woseseltops @vanlummelhuizen, please chip in.

**Comment by vanlummelhuizen** [comment]
Making a gloss unique within a dataset could mean several things, I think.

1. A gloss could belong to multiple datasets. This would involve changing a one-to-many relationship (each dataset may contain many glosses; each gloss belongs to *one* dataset) to a many-to-many relationship (each dataset may contain many glosses; each gloss belongs to *multiple* datasets)
2. The annotation_idgloss is now defined as 'unique', so it may be used as a gloss identifier within the whole database. We may define the combination of annotation_idgloss and dataset as unique. In that case an annotation_idgloss may be used in multiple glosses, as long as they don't belong to the same dataset.

Both involves database changes.

The example suggests the latter is what you want. Correct, @ocrasborn ?

**Comment by ocrasborn** [comment]
Yes, indeed. Top priority, I would say.

**Comment by vanlummelhuizen** [comment]
@ocrasborn OK. I need to do some thinking because I am also in the process of making idgloss and annotation_idgloss multilingual. The latter already has a Dutch version and an English version (suffix '_en'), but it needs to be dynamic. 

If you hear some strange squeaks coming from my room, that's my brain ;)

**Comment by vanlummelhuizen** [comment]
Thinking out loud:

If we have a table for Annotation_idglosses that has a one-to-many relationship with Gloss (a gloss may have many annotation_idglosses, an annotation_idgloss only has one gloss), and a one-to-many relationship with (spoken) Language (each annotation_idgloss has one language, a language may be linked to many annotation_idglosses). If we then make the combination of gloss and language unique in the Annotation_idgloss table, an annotation_idgloss is unique for a dataset as well because a gloss is unique for a dataset.

I am going to let this soak now during the coffee break (while drinking tea).

**Comment by vanlummelhuizen** [comment]
One potential problem has come up for the solution I wrote earlier. It is necessary to check that the language of annotation_idgloss is one of the languages of the dataset of the gloss of that annotation_idgloss (note the circularity here). Ideally, this check should be on the database side, so we don't have to worry about it too much in the Django code (there could be many places where we need to check this). 

There is a similar problem for gloss -> dataset -> signlanguage and gloss -> dialect -> signlanguage.

While writing this, I was thinking: is it enough to overwrite the save method for annotation_idgloss and gloss respectivly?

**Comment by vanlummelhuizen** [comment]
OK, overriding the save methods could be a solution, but there are some caveats.

From https://docs.djangoproject.com/en/1.11/topics/db/models/#overriding-model-methods:

> Overridden model methods are not called on bulk operations
>
> Note that the delete() method for an object is not necessarily called when deleting objects in bulk using a QuerySet or as a result of a cascading delete. To ensure customized delete logic gets executed, you can use pre_delete and/or post_delete signals.
>
> Unfortunately, there isn’t a workaround when creating or updating objects in bulk, since none of save(), pre_save, and post_save are called.

So we need to take of those as well.

**Comment by henrinie** [comment]
I am trying to get my head around this, I hope that I am not confusing you too much.
It seems that this could become quite complex quite fast. I guess the question is: **What needs to be unique and where?**
Btw, you seem to refer to `annotation_idgloss`, how is this different to `idgloss`? Do you need both?

@vanlummelhuizen Would the annotation_idgloss tables rows only be translations of a Gloss, or a Gloss of a Dataset? And would they need to be unique per Gloss, or per Gloss of a Dataset?

> glosses should be unique within datasets, but need not be unique between datasets. 
@ocrasborn what does it mean that glosses don't need to be unique between datasets?

> (Spoken analogy: I should be able to enter the form 'bank' in both English and Dutch, even though they may mean different things.)
Would you need to have different translations for Glosses based on their Dataset? If not, and you would only need to translate the Gloss, it would sound like a one to one relationship to me.

Thinking out loud:
So if a Gloss (idgloss or annotation_idgloss) would be translated and the uniqueness of the translation would be enforced per Gloss, I think it would be easy, but you could only use each translation once (per language).

If you want to have unique translations of Glosses within Datasets, it can get really complicated. This would mean that one Gloss could have multiple translations (per language) depending on its Dataset.


@vanlummelhuizen So if the uniqueness is per Gloss, you could just add more fields to the Gloss model for each language (as it is one-to-one). This way there would not be any conflicts within the database, and the uniqueness could be easily enforced within the database level. Django-modeltranslation handles translations of model fields like this, and I guess it would be just easiest to do with it.
If you want to create a new model for the translations, it shouldn't be too difficult, you could enforce uniqueness with `unique_together` based on the Gloss and the Language.

**Comment by ocrasborn** [comment]
@henrinie asked: "@ocrasborn what does it mean that glosses don't need to be unique between datasets?" --> the same word (say, again, 'bank') could be a unique value for multiple datasets. So it's not necessary to enforce uniqueness across datasets.
Maybe as a background, which I think might help your puzzledness: we don't expect to have many datasets for the same sign language, perhaps occasionally a small one for student use, so for us it's not so important that a sign form has the same gloss (i.e., an "ID" gloss) in different datasets. For your case, the two FinSL datasets, it could be very useful that different groups who manage the different datasets agree on identical glosses.

**Comment by vanlummelhuizen** [comment]
@henrinie 

> It seems that this could become quite complex quite fast.

I couldn't agree more. :s

> If you want to have unique translations of Glosses within Datasets, it can get really complicated. This would mean that one Gloss could have multiple translations (per language) depending on its Dataset.

Yup. An quite complex indeed.

The complexity come from the fact that the set of languages that are used to describe a gloss (number 3 as described by Wessel in https://github.com/Signbank/NGT-signbank/issues/182#issuecomment-261505047) may differ from dataset to dataset. That means that adding another annotation_idgloss for a new language is not dynamic enough. The same goes for using the django-modeltranslation module.

**Comment by ocrasborn** [comment]
Oh, yes, and another thing I wanted to explain that might help: these glosses will never be the sole way we will match signs across languages (and thus across datasets). After all, they're just convenient IDentifiers. Matching a sign in one dataset to one in another one (to see whether 'dog' has the same form in language A and language B) would always happen through the translation equivalents/keywords.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , the importing works now; if there's any to do's left from the discussion, perhaps move them to a new issue?

**Comment by vanlummelhuizen** [comment]
@ocrasborn I don't see anything that we did not deal with. Close?

**Comment by ocrasborn** [comment]
Agree, @vanlummelhuizen . Close.
