### ISSUE TITLE
Make list of morphology types editable in Django admin

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#83]
(that is: the values in the pull-downmenu Type in the Morphology panel)

**Comment by susanodd** [comment]
This is available here: From your signbank location...  navigate as shown: Admin, Dictionary, Field choices, MorphemeType is in the list on the right.
/admin/dictionary/fieldchoice/?field=MorphemeType

**Comment by ocrasborn** [comment]
Thanks @susanodd !
